<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>D Computer practical 4 - Analysis for Binary and Survival data | Clinical Trials 4H</title>
  <meta name="description" content="These notes mirror what we’ll follow in lectures for Clinical Trials 4H. If you have any questions or notice any errors, please email me (Rachel Oughton)." />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="D Computer practical 4 - Analysis for Binary and Survival data | Clinical Trials 4H" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="These notes mirror what we’ll follow in lectures for Clinical Trials 4H. If you have any questions or notice any errors, please email me (Rachel Oughton)." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="D Computer practical 4 - Analysis for Binary and Survival data | Clinical Trials 4H" />
  
  <meta name="twitter:description" content="These notes mirror what we’ll follow in lectures for Clinical Trials 4H. If you have any questions or notice any errors, please email me (Rachel Oughton)." />
  

<meta name="author" content="Rachel Oughton" />


<meta name="date" content="2026-03-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="cp3sim.html"/>
<link rel="next" href="cp-missing.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>
<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome to Clinical Trials 4H!</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#practical-details"><i class="fa fa-check"></i>Practical details</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#lectures"><i class="fa fa-check"></i>Lectures</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#computer-classes"><i class="fa fa-check"></i>Computer classes</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#office-hour"><i class="fa fa-check"></i>Office Hour</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#assessment"><i class="fa fa-check"></i>Assessment</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#books-and-resources"><i class="fa fa-check"></i>Books and resources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#what-to-expect-from-this-module"><i class="fa fa-check"></i>What to expect from this module</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#what-i-expect-from-you"><i class="fa fa-check"></i>What I expect from you</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="rct-intro.html"><a href="rct-intro.html"><i class="fa fa-check"></i><b>1</b> Introduction to Clinical Trials</a>
<ul>
<li class="chapter" data-level="1.1" data-path="rct-intro.html"><a href="rct-intro.html#causal-inference-and-clinical-trials"><i class="fa fa-check"></i><b>1.1</b> Causal inference and clinical trials</a></li>
<li class="chapter" data-level="1.2" data-path="rct-intro.html"><a href="rct-intro.html#primout"><i class="fa fa-check"></i><b>1.2</b> The structure of a clinical trial</a>
<ul>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#the-population-of-eligible-patients"><i class="fa fa-check"></i>The population of eligible patients</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#entry-to-the-trial"><i class="fa fa-check"></i>Entry to the trial</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#allocation-to-groups"><i class="fa fa-check"></i>Allocation to groups</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#the-primary-outcome"><i class="fa fa-check"></i>The primary outcome</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#comparing-results"><i class="fa fa-check"></i>Comparing results</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#trial-timeline"><i class="fa fa-check"></i>Trial timeline</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#trial-protocol-and-analysis-plan"><i class="fa fa-check"></i>Trial protocol and analysis plan</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#why-bother-with-a-control-group"><i class="fa fa-check"></i>Why bother with a control group?</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="rct-intro.html"><a href="rct-intro.html#ethical-issues"><i class="fa fa-check"></i><b>1.3</b> Ethical issues</a></li>
<li class="chapter" data-level="1.4" data-path="rct-intro.html"><a href="rct-intro.html#phases-of-clinical-trials"><i class="fa fa-check"></i><b>1.4</b> Phases of clinical trials</a>
<ul>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-zero"><i class="fa fa-check"></i>Phase zero</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-one"><i class="fa fa-check"></i>Phase one</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-two"><i class="fa fa-check"></i>Phase two</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-three"><i class="fa fa-check"></i>Phase three</a></li>
<li class="chapter" data-level="" data-path="rct-intro.html"><a href="rct-intro.html#phase-four"><i class="fa fa-check"></i>Phase four</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>I Part I: Continuous outcome variables</b></span></li>
<li class="chapter" data-level="2" data-path="rct-plan.html"><a href="rct-plan.html"><i class="fa fa-check"></i><b>2</b> Sample size for a normally distributed primary outcome variable</a>
<ul>
<li class="chapter" data-level="2.1" data-path="rct-plan.html"><a href="rct-plan.html#the-treatment-effect"><i class="fa fa-check"></i><b>2.1</b> The treatment effect</a></li>
<li class="chapter" data-level="2.2" data-path="rct-plan.html"><a href="rct-plan.html#reminder-hypothesis-tests-with-a-focus-on-rcts"><i class="fa fa-check"></i><b>2.2</b> Reminder: hypothesis tests (with a focus on RCTs)</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="rct-plan.html"><a href="rct-plan.html#one-tailed-or-two-tailed"><i class="fa fa-check"></i><b>2.2.1</b> One-tailed or two-tailed?</a></li>
<li class="chapter" data-level="2.2.2" data-path="rct-plan.html"><a href="rct-plan.html#insignificant-results"><i class="fa fa-check"></i><b>2.2.2</b> Insignificant results</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="rct-plan.html"><a href="rct-plan.html#sec-measDcont"><i class="fa fa-check"></i><b>2.3</b> Constructing a measure of effect size</a></li>
<li class="chapter" data-level="2.4" data-path="rct-plan.html"><a href="rct-plan.html#sec-power"><i class="fa fa-check"></i><b>2.4</b> Power: If <span class="math inline">\(H_0\)</span> is false</a></li>
<li class="chapter" data-level="2.5" data-path="rct-plan.html"><a href="rct-plan.html#sec-ssformulacont"><i class="fa fa-check"></i><b>2.5</b> A sample size formula</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="alloc.html"><a href="alloc.html"><i class="fa fa-check"></i><b>3</b> Allocation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="alloc.html"><a href="alloc.html#bias"><i class="fa fa-check"></i><b>3.1</b> Bias</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="alloc.html"><a href="alloc.html#where-does-bias-come-from"><i class="fa fa-check"></i><b>3.1.1</b> Where does bias come from?</a></li>
<li class="chapter" data-level="3.1.2" data-path="alloc.html"><a href="alloc.html#implications-for-allocation"><i class="fa fa-check"></i><b>3.1.2</b> Implications for allocation</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="alloc.html"><a href="alloc.html#sec-allocation"><i class="fa fa-check"></i><b>3.2</b> Allocation methods</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="alloc.html"><a href="alloc.html#simple-random-allocation"><i class="fa fa-check"></i><b>3.2.1</b> Simple random allocation</a></li>
<li class="chapter" data-level="3.2.2" data-path="alloc.html"><a href="alloc.html#random-permuted-blocks"><i class="fa fa-check"></i><b>3.2.2</b> Random permuted blocks</a></li>
<li class="chapter" data-level="3.2.3" data-path="alloc.html"><a href="alloc.html#bcurn"><i class="fa fa-check"></i><b>3.2.3</b> Biased coin designs and urn schemes</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="alloc.html"><a href="alloc.html#incorporating-baseline-measurements"><i class="fa fa-check"></i><b>3.3</b> Incorporating baseline measurements</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="alloc.html"><a href="alloc.html#stratified-sampling"><i class="fa fa-check"></i><b>3.3.1</b> Stratified sampling</a></li>
<li class="chapter" data-level="3.3.2" data-path="alloc.html"><a href="alloc.html#minimization"><i class="fa fa-check"></i><b>3.3.2</b> Minimization</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="alloc.html"><a href="alloc.html#problems-around-allocation"><i class="fa fa-check"></i><b>3.4</b> Problems around allocation</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="rct-analysis.html"><a href="rct-analysis.html"><i class="fa fa-check"></i><b>4</b> Analyzing RCT data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="rct-analysis.html"><a href="rct-analysis.html#ttest"><i class="fa fa-check"></i><b>4.1</b> Confidence intervals and P-values</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="rct-analysis.html"><a href="rct-analysis.html#what-do-we-do-with-this-outcome"><i class="fa fa-check"></i><b>4.1.1</b> What do we do with this outcome?</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="rct-analysis.html"><a href="rct-analysis.html#baseline"><i class="fa fa-check"></i><b>4.2</b> Using baseline values</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="rct-analysis.html"><a href="rct-analysis.html#the-variance-of-the-treatment-effect-estimate"><i class="fa fa-check"></i><b>4.2.1</b> The variance of the treatment effect estimate</a></li>
<li class="chapter" data-level="4.2.2" data-path="rct-analysis.html"><a href="rct-analysis.html#a-dodgy-way-to-use-baseline-variables"><i class="fa fa-check"></i><b>4.2.2</b> A dodgy way to use baseline variables</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="rct-analysis.html"><a href="rct-analysis.html#analysis-of-covariance-ancova"><i class="fa fa-check"></i><b>4.3</b> Analysis of covariance (ANCOVA)</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="rct-analysis.html"><a href="rct-analysis.html#ancovatheory"><i class="fa fa-check"></i><b>4.3.1</b> The theory</a></li>
<li class="chapter" data-level="4.3.2" data-path="rct-analysis.html"><a href="rct-analysis.html#ancova-practice"><i class="fa fa-check"></i><b>4.3.2</b> The practice</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="rct-analysis.html"><a href="rct-analysis.html#some-follow-up-questions."><i class="fa fa-check"></i><b>4.4</b> Some follow-up questions….</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="rct-analysis.html"><a href="rct-analysis.html#didnt-we-say-that-x_t---x_c-was-an-unbiased-estimator-of-tau"><i class="fa fa-check"></i><b>4.4.1</b> Didn’t we say that <span class="math inline">\(X_T - X_C\)</span> was an unbiased estimator of <span class="math inline">\(\tau\)</span>?</a></li>
<li class="chapter" data-level="4.4.2" data-path="rct-analysis.html"><a href="rct-analysis.html#what-if-the-lines-shouldnt-be-parallel-the-unequal-slopes-model"><i class="fa fa-check"></i><b>4.4.2</b> What if the lines shouldn’t be parallel? The unequal slopes model</a></li>
<li class="chapter" data-level="4.4.3" data-path="rct-analysis.html"><a href="rct-analysis.html#can-we-include-any-other-baseline-covariates"><i class="fa fa-check"></i><b>4.4.3</b> Can we include any other baseline covariates?</a></li>
<li class="chapter" data-level="" data-path="rct-analysis.html"><a href="rct-analysis.html#an-important-caution"><i class="fa fa-check"></i>An important caution!</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Part II: Binary outcome variable</b></span></li>
<li class="chapter" data-level="5" data-path="ss-bin.html"><a href="ss-bin.html"><i class="fa fa-check"></i><b>5</b> Sample size for a binary variable</a>
<ul>
<li class="chapter" data-level="5.1" data-path="ss-bin.html"><a href="ss-bin.html#delta-method"><i class="fa fa-check"></i><b>5.1</b> The Delta Method</a></li>
<li class="chapter" data-level="5.2" data-path="ss-bin.html"><a href="ss-bin.html#a-sample-size-formula"><i class="fa fa-check"></i><b>5.2</b> A sample size formula</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="binary-analysis.html"><a href="binary-analysis.html"><i class="fa fa-check"></i><b>6</b> Analysis for binary outcomes</a>
<ul>
<li class="chapter" data-level="6.1" data-path="binary-analysis.html"><a href="binary-analysis.html#bin-point-est"><i class="fa fa-check"></i><b>6.1</b> Simple hypothesis tests</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="binary-analysis.html"><a href="binary-analysis.html#a-simple-method-chi-squared"><i class="fa fa-check"></i><b>6.1.1</b> A simple method: chi-squared</a></li>
<li class="chapter" data-level="6.1.2" data-path="binary-analysis.html"><a href="binary-analysis.html#likelihood-a-more-rigorous-way"><i class="fa fa-check"></i><b>6.1.2</b> Likelihood: A more rigorous way</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="binary-analysis.html"><a href="binary-analysis.html#measures-of-difference-for-binary-data"><i class="fa fa-check"></i><b>6.2</b> Measures of difference for binary data</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="binary-analysis.html"><a href="binary-analysis.html#ard-and-nnt"><i class="fa fa-check"></i><b>6.2.1</b> Absolute risk difference and Number Needed to Treat</a></li>
<li class="chapter" data-level="6.2.2" data-path="binary-analysis.html"><a href="binary-analysis.html#risk-ratio-rr-and-odds-ratio-or"><i class="fa fa-check"></i><b>6.2.2</b> Risk Ratio (RR) and Odds ratio (OR)</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="binary-analysis.html"><a href="binary-analysis.html#logreg"><i class="fa fa-check"></i><b>6.3</b> Accounting for baseline observations: logistic regression</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="binary-analysis.html"><a href="binary-analysis.html#what-does-this-model-tell-us"><i class="fa fa-check"></i><b>6.3.1</b> What does this model tell us?</a></li>
<li class="chapter" data-level="6.3.2" data-path="binary-analysis.html"><a href="binary-analysis.html#fitting-a-logistic-regression-model"><i class="fa fa-check"></i><b>6.3.2</b> Fitting a logistic regression model</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="binary-analysis.html"><a href="binary-analysis.html#diaglogreg"><i class="fa fa-check"></i><b>6.4</b> Diagnostics for logistic regression</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="binary-analysis.html"><a href="binary-analysis.html#discrimination"><i class="fa fa-check"></i><b>6.4.1</b> Discrimination</a></li>
<li class="chapter" data-level="6.4.2" data-path="binary-analysis.html"><a href="binary-analysis.html#calibration"><i class="fa fa-check"></i><b>6.4.2</b> Calibration</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>III Part III: Survival data</b></span></li>
<li class="chapter" data-level="7" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html"><i class="fa fa-check"></i><b>7</b> Working with time-to-event data</a>
<ul>
<li class="chapter" data-level="7.1" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html#censored-times"><i class="fa fa-check"></i><b>7.1</b> Censored times</a></li>
<li class="chapter" data-level="7.2" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html#survhaz"><i class="fa fa-check"></i><b>7.2</b> The Survival Curve and the Hazard function</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html#the-kaplan-meier-estimator"><i class="fa fa-check"></i><b>7.2.1</b> The Kaplan-Meier estimator</a></li>
<li class="chapter" data-level="7.2.2" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html#surv-exp"><i class="fa fa-check"></i><b>7.2.2</b> A parametric approach</a></li>
<li class="chapter" data-level="7.2.3" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html#weibull"><i class="fa fa-check"></i><b>7.2.3</b> The Weibull distribution</a></li>
<li class="chapter" data-level="" data-path="working-with-time-to-event-data.html"><a href="working-with-time-to-event-data.html#aside-sample-size-calculations-for-time-to-event-data"><i class="fa fa-check"></i>Aside: Sample size calculations for time-to-event data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html"><i class="fa fa-check"></i><b>8</b> Comparing survival curves</a>
<ul>
<li class="chapter" data-level="8.1" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html#survlrtest"><i class="fa fa-check"></i><b>8.1</b> Parametric: likelihood ratio test</a></li>
<li class="chapter" data-level="8.2" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html#non-parametric-the-log-rank-test"><i class="fa fa-check"></i><b>8.2</b> Non-parametric: the log-rank test</a></li>
<li class="chapter" data-level="8.3" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html#semi-parametric-the-proportional-hazards-model"><i class="fa fa-check"></i><b>8.3</b> Semi-parametric: the proportional hazards model</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html#general-proportional-hazards-model"><i class="fa fa-check"></i><b>8.3.1</b> General proportional hazards model</a></li>
<li class="chapter" data-level="8.3.2" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html#coxreg"><i class="fa fa-check"></i><b>8.3.2</b> Cox regression</a></li>
<li class="chapter" data-level="" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html#how-can-we-tell-if-a-proportional-hazards-model-is-appropriate"><i class="fa fa-check"></i>How can we tell if a proportional hazards model is appropriate?</a></li>
<li class="chapter" data-level="8.3.3" data-path="comparing-survival-curves.html"><a href="comparing-survival-curves.html#diagnostics-for-cox-regression"><i class="fa fa-check"></i><b>8.3.3</b> Diagnostics for Cox regression</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Part III: Further designs</b></span></li>
<li class="chapter" data-level="9" data-path="cluster-rct.html"><a href="cluster-rct.html"><i class="fa fa-check"></i><b>9</b> Cluster randomised trials</a>
<ul>
<li class="chapter" data-level="9.1" data-path="cluster-rct.html"><a href="cluster-rct.html#what-is-a-cluster-rct"><i class="fa fa-check"></i><b>9.1</b> What is a cluster RCT?</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="cluster-rct.html"><a href="cluster-rct.html#intracluster-correlation"><i class="fa fa-check"></i><b>9.1.1</b> Intracluster correlation</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="cluster-rct.html"><a href="cluster-rct.html#sample-size"><i class="fa fa-check"></i><b>9.2</b> Sample size</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="cluster-rct.html"><a href="cluster-rct.html#ss-crt"><i class="fa fa-check"></i><b>9.2.1</b> A formula for sample size</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="cluster-rct.html"><a href="cluster-rct.html#allocation"><i class="fa fa-check"></i><b>9.3</b> Allocation</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="cluster-rct.html"><a href="cluster-rct.html#allocating-everyone-at-once"><i class="fa fa-check"></i><b>9.3.1</b> Allocating everyone at once</a></li>
<li class="chapter" data-level="9.3.2" data-path="cluster-rct.html"><a href="cluster-rct.html#covariate-constrained-randomization"><i class="fa fa-check"></i><b>9.3.2</b> Covariate constrained randomization</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="cluster-rct.html"><a href="cluster-rct.html#analysing-a-cluster-rct"><i class="fa fa-check"></i><b>9.4</b> Analysing a cluster RCT</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="cluster-rct.html"><a href="cluster-rct.html#at-the-cluster-level"><i class="fa fa-check"></i><b>9.4.1</b> At the cluster level</a></li>
<li class="chapter" data-level="9.4.2" data-path="cluster-rct.html"><a href="cluster-rct.html#at-the-individual-level-mixed-effects-models"><i class="fa fa-check"></i><b>9.4.2</b> At the individual level: mixed effects models</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="random-effects-for-individuals.html"><a href="random-effects-for-individuals.html"><i class="fa fa-check"></i><b>10</b> Random effects for individuals</a>
<ul>
<li class="chapter" data-level="10.1" data-path="random-effects-for-individuals.html"><a href="random-effects-for-individuals.html#crossover-trials"><i class="fa fa-check"></i><b>10.1</b> Crossover trials</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="random-effects-for-individuals.html"><a href="random-effects-for-individuals.html#the-abba-design"><i class="fa fa-check"></i><b>10.1.1</b> The AB/BA design</a></li>
<li class="chapter" data-level="10.1.2" data-path="random-effects-for-individuals.html"><a href="random-effects-for-individuals.html#analysis-of-the-abba-design"><i class="fa fa-check"></i><b>10.1.2</b> Analysis of the AB/BA design</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="random-effects-for-individuals.html"><a href="random-effects-for-individuals.html#longitudinal-data-repeated-measurements"><i class="fa fa-check"></i><b>10.2</b> Longitudinal data / repeated measurements</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="random-effects-for-individuals.html"><a href="random-effects-for-individuals.html#fitting-a-model"><i class="fa fa-check"></i><b>10.2.1</b> Fitting a model</a></li>
<li class="chapter" data-level="10.2.2" data-path="random-effects-for-individuals.html"><a href="random-effects-for-individuals.html#the-empty-model"><i class="fa fa-check"></i><b>10.2.2</b> The empty model</a></li>
<li class="chapter" data-level="" data-path="random-effects-for-individuals.html"><a href="random-effects-for-individuals.html#summary"><i class="fa fa-check"></i>Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="the-bayesian-approach.html"><a href="the-bayesian-approach.html"><i class="fa fa-check"></i><b>11</b> The Bayesian Approach</a>
<ul>
<li class="chapter" data-level="11.1" data-path="the-bayesian-approach.html"><a href="the-bayesian-approach.html#the-fundamental-difference"><i class="fa fa-check"></i><b>11.1</b> The fundamental difference</a>
<ul>
<li class="chapter" data-level="" data-path="the-bayesian-approach.html"><a href="the-bayesian-approach.html#the-frequentist-approach"><i class="fa fa-check"></i>The frequentist approach</a></li>
<li class="chapter" data-level="" data-path="the-bayesian-approach.html"><a href="the-bayesian-approach.html#the-bayesian-approach-1"><i class="fa fa-check"></i>The Bayesian approach</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="the-bayesian-approach.html"><a href="the-bayesian-approach.html#why-is-this-important"><i class="fa fa-check"></i><b>11.2</b> Why is this important?</a>
<ul>
<li class="chapter" data-level="" data-path="the-bayesian-approach.html"><a href="the-bayesian-approach.html#making-probabilistic-statements-about-the-treatment-effect"><i class="fa fa-check"></i>Making probabilistic statements about the treatment effect</a></li>
<li class="chapter" data-level="" data-path="the-bayesian-approach.html"><a href="the-bayesian-approach.html#sequential-analysis"><i class="fa fa-check"></i>Sequential analysis</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="the-bayesian-approach.html"><a href="the-bayesian-approach.html#how-do-we-choose-a-prior"><i class="fa fa-check"></i><b>11.3</b> How do we choose a prior?</a>
<ul>
<li class="chapter" data-level="" data-path="the-bayesian-approach.html"><a href="the-bayesian-approach.html#a-reference-prior"><i class="fa fa-check"></i>A reference prior</a></li>
<li class="chapter" data-level="" data-path="the-bayesian-approach.html"><a href="the-bayesian-approach.html#a-clinical-prior"><i class="fa fa-check"></i>A clinical prior</a></li>
<li class="chapter" data-level="" data-path="the-bayesian-approach.html"><a href="the-bayesian-approach.html#a-sceptical-prior"><i class="fa fa-check"></i>A sceptical prior</a></li>
<li class="chapter" data-level="" data-path="the-bayesian-approach.html"><a href="the-bayesian-approach.html#an-optimistic-enthusiastic-prior"><i class="fa fa-check"></i>An optimistic / enthusiastic prior</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="the-bayesian-approach.html"><a href="the-bayesian-approach.html#more-complex-trials"><i class="fa fa-check"></i><b>11.4</b> More complex trials</a></li>
</ul></li>
<li class="appendix"><span><b>Computer practicals</b></span></li>
<li class="chapter" data-level="A" data-path="cp1allocation.html"><a href="cp1allocation.html"><i class="fa fa-check"></i><b>A</b> Computer Practical 1 - Allocation</a>
<ul>
<li class="chapter" data-level="A.1" data-path="cp1allocation.html"><a href="cp1allocation.html#cprprac"><i class="fa fa-check"></i><b>A.1</b> R practicalities</a></li>
<li class="chapter" data-level="A.2" data-path="cp1allocation.html"><a href="cp1allocation.html#allocation-1"><i class="fa fa-check"></i><b>A.2</b> Allocation</a>
<ul>
<li class="chapter" data-level="A.2.1" data-path="cp1allocation.html"><a href="cp1allocation.html#licorice-gargle-dataset"><i class="fa fa-check"></i><b>A.2.1</b> Licorice gargle dataset</a></li>
<li class="chapter" data-level="A.2.2" data-path="cp1allocation.html"><a href="cp1allocation.html#measures-of-imbalance"><i class="fa fa-check"></i><b>A.2.2</b> Measures of imbalance</a></li>
<li class="chapter" data-level="A.2.3" data-path="cp1allocation.html"><a href="cp1allocation.html#allocmethods"><i class="fa fa-check"></i><b>A.2.3</b> Allocation methods</a></li>
<li class="chapter" data-level="A.2.4" data-path="cp1allocation.html"><a href="cp1allocation.html#stratifying-the-dataset"><i class="fa fa-check"></i><b>A.2.4</b> Stratifying the dataset</a></li>
<li class="chapter" data-level="A.2.5" data-path="cp1allocation.html"><a href="cp1allocation.html#minimisation"><i class="fa fa-check"></i><b>A.2.5</b> Minimisation</a></li>
<li class="chapter" data-level="A.2.6" data-path="cp1allocation.html"><a href="cp1allocation.html#extension-a-simulation-experiment"><i class="fa fa-check"></i><b>A.2.6</b> Extension: A simulation experiment!</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="cp2analysis.html"><a href="cp2analysis.html"><i class="fa fa-check"></i><b>B</b> Computer Practical 2 - Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="cp2analysis.html"><a href="cp2analysis.html#preliminaries"><i class="fa fa-check"></i>Preliminaries</a>
<ul>
<li class="chapter" data-level="" data-path="cp2analysis.html"><a href="cp2analysis.html#r-practicalities"><i class="fa fa-check"></i>R practicalities</a></li>
</ul></li>
<li class="chapter" data-level="B.1" data-path="cp2analysis.html"><a href="cp2analysis.html#cp1analysis"><i class="fa fa-check"></i><b>B.1</b> Analysis</a>
<ul>
<li class="chapter" data-level="B.1.1" data-path="cp2analysis.html"><a href="cp2analysis.html#polyps-data"><i class="fa fa-check"></i><b>B.1.1</b> Polyps data</a></li>
<li class="chapter" data-level="B.1.2" data-path="cp2analysis.html"><a href="cp2analysis.html#extension-treatment-for-maternal-periodontal-disease"><i class="fa fa-check"></i><b>B.1.2</b> Extension: Treatment for maternal periodontal disease</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="C" data-path="cp3sim.html"><a href="cp3sim.html"><i class="fa fa-check"></i><b>C</b> Computer Practical 3 - Sample size by simulation</a>
<ul>
<li class="chapter" data-level="C.1" data-path="cp3sim.html"><a href="cp3sim.html#power-simulation-for-a-t-test"><i class="fa fa-check"></i><b>C.1</b> Power simulation for a t-test</a></li>
<li class="chapter" data-level="C.2" data-path="cp3sim.html"><a href="cp3sim.html#power-simulation-for-ancova"><i class="fa fa-check"></i><b>C.2</b> Power simulation for ANCOVA</a></li>
<li class="chapter" data-level="C.3" data-path="cp3sim.html"><a href="cp3sim.html#conclusion"><i class="fa fa-check"></i><b>C.3</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="computer-practical-4---analysis-for-binary-and-survival-data.html"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html"><i class="fa fa-check"></i><b>D</b> Computer practical 4 - Analysis for Binary and Survival data</a>
<ul>
<li class="chapter" data-level="D.1" data-path="computer-practical-4---analysis-for-binary-and-survival-data.html"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#binary-outcome-data"><i class="fa fa-check"></i><b>D.1</b> Binary outcome data</a>
<ul>
<li class="chapter" data-level="D.1.1" data-path="computer-practical-4---analysis-for-binary-and-survival-data.html"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cp2logreg"><i class="fa fa-check"></i><b>D.1.1</b> Logistic regression</a></li>
</ul></li>
<li class="chapter" data-level="D.2" data-path="computer-practical-4---analysis-for-binary-and-survival-data.html"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cp2-surv"><i class="fa fa-check"></i><b>D.2</b> Analysis for Survival data</a>
<ul>
<li class="chapter" data-level="D.2.1" data-path="computer-practical-4---analysis-for-binary-and-survival-data.html"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#fitting-a-survival-curve"><i class="fa fa-check"></i><b>D.2.1</b> Fitting a survival curve</a></li>
<li class="chapter" data-level="D.2.2" data-path="computer-practical-4---analysis-for-binary-and-survival-data.html"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#comparing-survival-curves-1"><i class="fa fa-check"></i><b>D.2.2</b> Comparing survival curves</a></li>
</ul></li>
<li class="chapter" data-level="D.3" data-path="computer-practical-4---analysis-for-binary-and-survival-data.html"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cp4sim2"><i class="fa fa-check"></i><b>D.3</b> Extension problem: sample size by simulation (part II)</a>
<ul>
<li class="chapter" data-level="D.3.1" data-path="computer-practical-4---analysis-for-binary-and-survival-data.html"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#minimum-detectable-effect-size"><i class="fa fa-check"></i><b>D.3.1</b> Minimum detectable effect size</a></li>
<li class="chapter" data-level="D.3.2" data-path="computer-practical-4---analysis-for-binary-and-survival-data.html"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#censoring"><i class="fa fa-check"></i><b>D.3.2</b> Censoring</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="E" data-path="cp-missing.html"><a href="cp-missing.html"><i class="fa fa-check"></i><b>E</b> Extra Computer Practical - Missing data</a>
<ul>
<li class="chapter" data-level="" data-path="cp-missing.html"><a href="cp-missing.html#r-practicalities-1"><i class="fa fa-check"></i>R practicalities</a></li>
<li class="chapter" data-level="E.1" data-path="cp-missing.html"><a href="cp-missing.html#missing-data"><i class="fa fa-check"></i><b>E.1</b> Missing data</a>
<ul>
<li class="chapter" data-level="E.1.1" data-path="cp-missing.html"><a href="cp-missing.html#datasets"><i class="fa fa-check"></i><b>E.1.1</b> Datasets</a></li>
</ul></li>
<li class="chapter" data-level="E.2" data-path="cp-missing.html"><a href="cp-missing.html#understanding-the-patterns-of-missingness"><i class="fa fa-check"></i><b>E.2</b> Understanding the patterns of missingness</a>
<ul>
<li class="chapter" data-level="E.2.1" data-path="cp-missing.html"><a href="cp-missing.html#visualising-missingness"><i class="fa fa-check"></i><b>E.2.1</b> Visualising missingness</a></li>
<li class="chapter" data-level="E.2.2" data-path="cp-missing.html"><a href="cp-missing.html#summary-tables-1"><i class="fa fa-check"></i><b>E.2.2</b> Summary tables</a></li>
<li class="chapter" data-level="E.2.3" data-path="cp-missing.html"><a href="cp-missing.html#mechanisms-of-missingness"><i class="fa fa-check"></i><b>E.2.3</b> Mechanisms of missingness</a></li>
</ul></li>
<li class="chapter" data-level="E.3" data-path="cp-missing.html"><a href="cp-missing.html#exploring-the-relationship-between-missingness-and-other-variables"><i class="fa fa-check"></i><b>E.3</b> Exploring the relationship between missingness and other variables</a>
<ul>
<li class="chapter" data-level="E.3.1" data-path="cp-missing.html"><a href="cp-missing.html#sec-statsum"><i class="fa fa-check"></i><b>E.3.1</b> Statistical summaries of the effect of missingness</a></li>
<li class="chapter" data-level="E.3.2" data-path="cp-missing.html"><a href="cp-missing.html#modelling-missingness"><i class="fa fa-check"></i><b>E.3.2</b> Modelling missingness</a></li>
</ul></li>
<li class="chapter" data-level="E.4" data-path="cp-missing.html"><a href="cp-missing.html#what-to-do-about-missing-data"><i class="fa fa-check"></i><b>E.4</b> What to do about missing data?!</a>
<ul>
<li class="chapter" data-level="E.4.1" data-path="cp-missing.html"><a href="cp-missing.html#discarding-some-non-missing-data"><i class="fa fa-check"></i><b>E.4.1</b> Discarding some (non-missing) data</a></li>
<li class="chapter" data-level="E.4.2" data-path="cp-missing.html"><a href="cp-missing.html#imputing-data"><i class="fa fa-check"></i><b>E.4.2</b> Imputing data</a></li>
<li class="chapter" data-level="E.4.3" data-path="cp-missing.html"><a href="cp-missing.html#multiple-imputation"><i class="fa fa-check"></i><b>E.4.3</b> Multiple imputation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Clinical Trials 4H</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="computer-practical-4---analysis-for-binary-and-survival-data" class="section level1 hasAnchor" number="15">
<h1><span class="header-section-number">D</span> Computer practical 4 - Analysis for Binary and Survival data<a href="computer-practical-4---analysis-for-binary-and-survival-data.html#computer-practical-4---analysis-for-binary-and-survival-data" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<details>
<summary>
<strong>R practicalities - click here</strong>
</summary>
<p>There are many, many packages in R that implement methods for designing and analysing clinical trials (see a list at <a href="https://cran.r-project.org/web/views/ClinicalTrials.html">CRAN task view</a>). We will look at some of these, and will also write our own code for some tasks. Remember that to install a package, you can do</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb236-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;&lt;packagename&gt;&quot;</span>)</span></code></pre></div>
<p>If you have problems running R on your laptop, or on the university machines, the most foolproof way might be to use Github codespaces (thanks to Louis Aslett, who developed this). You may already be familiar with this from previous modules.</p>
<p>An advantage of this is that you can open the same codespace (the same instance of R) from any computer, so if you plan to work on things (for example your summative assignment, which will involve some R) from more than one computer, this might be ideal.</p>
<p>Here is a <a href="https://www.louisaslett.com/Courses/DSSM/notes/installr.html#codespaces">guide to getting set up</a>.</p>
<p><a href="https://codespaces.new/louisaslett/dssm?quickstart=1">Direct link to codespace</a></p>
</details>
<p>In this practical we’ll focus on the analysis of binary and survival data. We’ll make use of several new packages. Installing them all now should hopefully prevent it from disrupting your flow! We’ll load them as we go along.</p>
<p><strong>Notice that where there are code snippets that you want to copy directly, you can hover your cursor in the top right of the code box and a ‘copy’ icon will appear.</strong></p>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb237-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">&quot;tidyverse&quot;</span>, <span class="st">&quot;HSAUR&quot;</span>, <span class="st">&quot;HSAUR3&quot;</span>, <span class="st">&quot;pROC&quot;</span>, <span class="st">&quot;survival&quot;</span>, <span class="st">&quot;ggsurvfit&quot;</span>, <span class="st">&quot;survminer&quot;</span>, <span class="st">&quot;car&quot;</span>))</span></code></pre></div>
<div id="binary-outcome-data" class="section level2 hasAnchor" number="15.1">
<h2><span class="header-section-number">D.1</span> Binary outcome data<a href="computer-practical-4---analysis-for-binary-and-survival-data.html#binary-outcome-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The dataset we’ll use to explore Binary outcome data is the <code>respiratory</code> dataset, from the package <code>HSAUR</code>. In this trial, patients across two centres were randomly assigned to receive treatment or placebo, and their respiratory status was recorded as either ‘poor’ or ‘good’. Measurements were recorded at months 0, 1, 2, 3, 4, but we will keep only month 0 (as a baseline) and month 4 (as a final outcome). We process the data below:</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb238-1" tabindex="-1"></a><span class="fu">library</span>(HSAUR)</span>
<span id="cb238-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb238-2" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;respiratory&quot;</span>)</span>
<span id="cb238-3"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb238-3" tabindex="-1"></a><span class="co"># Keep only months 0 and 4</span></span>
<span id="cb238-4"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb238-4" tabindex="-1"></a>resp_04 <span class="ot">=</span> respiratory <span class="sc">|&gt;</span></span>
<span id="cb238-5"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb238-5" tabindex="-1"></a>  <span class="fu">filter</span>(month <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">4</span>))</span>
<span id="cb238-6"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb238-6" tabindex="-1"></a></span>
<span id="cb238-7"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb238-7" tabindex="-1"></a><span class="do">## convert to wider to have one row per participant</span></span>
<span id="cb238-8"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb238-8" tabindex="-1"></a>resp_df <span class="ot">=</span> <span class="fu">pivot_wider</span>(</span>
<span id="cb238-9"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb238-9" tabindex="-1"></a>  <span class="at">data =</span> resp_04, </span>
<span id="cb238-10"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb238-10" tabindex="-1"></a>  <span class="at">id_cols =</span> <span class="fu">c</span>(<span class="st">&quot;subject&quot;</span>, <span class="st">&quot;centre&quot;</span>, <span class="st">&quot;treatment&quot;</span>, <span class="st">&quot;sex&quot;</span>, <span class="st">&quot;age&quot;</span>),</span>
<span id="cb238-11"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb238-11" tabindex="-1"></a>  <span class="at">names_from =</span> <span class="st">&quot;month&quot;</span>,</span>
<span id="cb238-12"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb238-12" tabindex="-1"></a>  <span class="at">names_prefix =</span> <span class="st">&quot;status&quot;</span>,</span>
<span id="cb238-13"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb238-13" tabindex="-1"></a>  <span class="at">values_from =</span> <span class="st">&quot;status&quot;</span></span>
<span id="cb238-14"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb238-14" tabindex="-1"></a>)</span></code></pre></div>
<p>For each patient, we have the following baseline covariates:</p>
<ul>
<li>sex</li>
<li>age</li>
<li>treatment centre (centre 1 or centre 2)</li>
<li>symptom status (poor or good).</li>
</ul>
<p>The outcome variable is whether the status of the patient’s symptoms are poor or good after four months of the trial. Note that unusually we do have the baseline observation of this quantity. Since a lot of the earlier methods we covered in Chapter <a href="binary-analysis.html#binary-analysis">6</a> involve simple calculations with the data (and working with survival data is much less familiar), we will skip straight logistic regression.</p>
<!-- ### Confidence Intervals -->
<!-- Our first step will be to fit a Wilson confidence interval for the absolute risk difference, as we did in Section \@ref(newcombeci). Recall that the limits of a $100(1-\alpha)\%$ CI for the ARD $\pi_T - \pi_C$ are given by -->
<!-- $$ -->
<!-- \left(p_T - p_C - \sqrt{\left(p_T-l_T\right)^2 + \left(u_C - p_C\right)^2},\; p_T - p_C + \sqrt{\left(u_T - p_T\right)^2 + \left(p_C - l_C\right)^2}\right), -->
<!-- $$ -->
<!-- where $p_X$ is the estimate of $\pi_X$ (for group $X$), and $\left(l_X,\,u_X\right)$ is the $100\left(1-\alpha\right)\%$ CI for $\pi_X$. The limits of the $100\left(1-\alpha\right)\%$ Wilson CI for $\pi_X$ are given by the roots of the equation (in $\pi_X$) -->
<!-- $$ -->
<!-- \left(p_X - \pi_X\right)^2 = z^2_{\frac{\alpha}{2}}\frac{\pi_X\left(1-\pi_X\right)}{n}. -->
<!-- $$ -->
<!-- :::{.exercise #Wilson} -->
<!-- Using only the final / month 4 outcomes, find the Wilson 95% CI for the ARD for the `resp_df` dataset we made above, treating a 'good' respiratory status as 1 and a 'poor' respiratory status as 0. Translate this into a confidence interval for the number needed to treat (NNT). Comment on the result. -->
<!-- ::: -->
<!-- <details> <summary> Click for solution </summary> -->
<!-- :::{.solution} -->
<!-- The first thing we need to do is to find the limits of the individual CIs for groups C and T.  -->
<!-- To do this, we need the data estimates of $p_C$ and $p_T$. -->
<!-- ```{r, echo=T} -->
<!-- rC = sum((resp_df$status == "good")&(resp_df$treatment == "placebo")) -->
<!-- nC = sum(resp_df$treatment == "placebo") -->
<!-- pC = rC / nC -->
<!-- rT = sum((resp_df$status == "good")&(resp_df$treatment == "treatment")) -->
<!-- nT = sum(resp_df$treatment == "treatment") -->
<!-- pT = rT / nT -->
<!-- ``` -->
<!-- To find the limits of the individual CIs, we need to rearrange the quadratic equation above into the form we're used to -->
<!-- $$\left(1 + \frac{z^2}{n}\right)\pi^2  + \left(-2p-\frac{z^2}{n}\right)\pi + p^2 = 0.$$ -->
<!-- It is simple to define a function to solve quadratic equations in this form, for example -->
<!-- ```{r, echo=T} -->
<!-- quad_fun = function(a,b,c){ -->
<!--   disc = b^2 - 4*a*c -->
<!--   lower = (-b - sqrt(disc))/(2*a) -->
<!--   upper = (-b + sqrt(disc))/(2*a) -->
<!--   c(lower, upper) -->
<!-- } -->
<!-- ``` -->
<!-- and we can now find the limits of each CI: -->
<!-- ```{r, echo=T} -->
<!-- # Control group -->
<!-- lim_resp_C = quad_fun( -->
<!--   a = 1 + qnorm(0.975)^2/nC, -->
<!--   b = -2*pC - qnorm(0.975)^2/nC, -->
<!--   c = pC^2 -->
<!-- ) -->
<!-- lim_resp_C -->
<!-- # Treatment group -->
<!-- lim_resp_T = quad_fun( -->
<!--   a = 1 + qnorm(0.975)^2/nT, -->
<!--   b = -2*pT - qnorm(0.975)^2/nT, -->
<!--   c = pT^2 -->
<!-- ) -->
<!-- lim_resp_T -->
<!-- ``` -->
<!-- Notice that because $p_C$ is quite close to 0.5, the Newcome interval for $\pi_C$ is close to symmetric. The CI for $\pi_T$ is more skewed. -->
<!-- Finally we can use these values to find the Wilson CI for the ARD: -->
<!-- ```{r, echo=T} -->
<!-- # Make objects match notation -->
<!-- lC = lim_resp_C[1] -->
<!-- uC = lim_resp_C[2] -->
<!-- lT = lim_resp_T[1] -->
<!-- uT = lim_resp_T[2] -->
<!-- l_newc = pT - pC - sqrt((pT - lT)^2 + (uC - pC)^2) -->
<!-- u_newc = pT - pC + sqrt((uT - pT)^2 + (pC - lC)^2) -->
<!-- c(l_newc, u_newc) -->
<!-- ``` -->
<!-- Finally we can use this to find a 95% CI for the NNT by finding the reciprocals of the limits of the CI for ARD: -->
<!-- ```{r, echo=T} -->
<!-- c(1/u_newc, 1/l_newc) -->
<!-- ``` -->
<!-- This is a huge range and would make it difficult to make a clinical decision. -->
<!-- ::: -->
<!-- </details> -->
<!-- With the quantities we've found in exercise \@ref(exr:Wilson) we can also find an approximate 95% CI for the risk ratio (see Section \@ref(ci-rr)). -->
<!-- :::{.exercise #riskratio} -->
<!-- Find a 95% CI for the risk ratio $\frac{\pi_T}{\pi_C}$ and comment on your result. -->
<!-- ::: -->
<!-- <details> <summary> Click for solution </summary>  -->
<!-- :::{.solution} -->
<!-- Recall that the limits of the $100\left(1-\alpha\right)\%$ CI for the log of the risk ratio are given by -->
<!-- $$ \log\left(\frac{p_T}{p_C}\right) \pm z_{\frac{\alpha}{2}}\sqrt{\left(r_T^{-1} - n_T^{-1}\right) + \left(r_C^{-1} - n_C^{-1}\right)}. $$ -->
<!-- Therefore for our respiratory data we have -->
<!-- ```{r, echo=T} -->
<!-- # Find the estimated log OR and the distance to the limits of the CI -->
<!-- log_or_resp = log(pT/pC) -->
<!-- ci_diff = qnorm(0.975)*sqrt(1/rT - 1/nT + 1/rC - 1/nC) -->
<!-- # Calculate CI -->
<!-- ci_log_rr = c(log_or_resp - ci_diff, log_or_resp + ci_diff) -->
<!-- ci_log_rr -->
<!-- ``` -->
<!-- To transform this into a CI for the RR itself, we use -->
<!-- ```{r, echo=T} -->
<!-- exp(ci_log_rr) -->
<!-- ``` -->
<!-- This seems like a relatively narrow CI, but the fact that it comes so close to containing one (the 'null value' for the risk ratio) fits with the very large upper limit on the NNT / small lower limit on the ARD. Although this treatment appears significant, it may be that it has a very minimal effect in practice. -->
<!-- ::: -->
<!-- </details> -->
<div id="cp2logreg" class="section level3 hasAnchor" number="15.1.1">
<h3><span class="header-section-number">D.1.1</span> Logistic regression<a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cp2logreg" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Logistic regression give us a way to account for the baseline covariates. To fit a logistic regression in R we use the function <code>glm</code>. This fits all kinds of generalised linear models, and so we specify that we want a logistic regression by choosing <code>family = binomial(link='logit')</code>.</p>
<p>The code is included in all examples in Sections <a href="binary-analysis.html#logreg">6.3</a> and <a href="binary-analysis.html#diaglogreg">6.4</a>, so if you aren’t sure how to do something they would be a good place to look.</p>
<div class="exercise">
<p><span id="exr:lrresp1" class="exercise"><strong>Exercise D.1  </strong></span>Fit a logistic regression model to the <code>resp_df</code> data set, being careful to check for any issues with the data.</p>
</div>
<details>
<summary>
Click for solution
</summary>
<div class="solution">
<p><span id="unlabeled-div-108" class="solution"><em>Solution</em>. </span>The first model we fit involves all covariates linearly:</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb239-1" tabindex="-1"></a>model1 <span class="ot">=</span> <span class="fu">glm</span>(status4 <span class="sc">~</span> centre <span class="sc">+</span> treatment <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> status0, </span>
<span id="cb239-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb239-2" tabindex="-1"></a>             <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link=</span><span class="st">&#39;logit&#39;</span>), <span class="at">data=</span>resp_df)</span>
<span id="cb239-3"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb239-3" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = status4 ~ centre + treatment + sex + age + status0, 
##     family = binomial(link = &quot;logit&quot;), data = resp_df)
## 
## Coefficients:
##                    Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)        -0.83921    0.67498  -1.243 0.213757    
## centre2             1.27397    0.48546   2.624 0.008684 ** 
## treatmenttreatment  1.08498    0.47415   2.288 0.022122 *  
## sexmale             0.33480    0.60171   0.556 0.577924    
## age                -0.02978    0.01805  -1.650 0.099035 .  
## status0good         1.72562    0.47024   3.670 0.000243 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 153.44  on 110  degrees of freedom
## Residual deviance: 119.34  on 105  degrees of freedom
## AIC: 131.34
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>and we can inspect the variance inflation factor to check for multicollinearity:</p>
<pre><code>##    centre treatment       sex       age   status0 
##  1.171418  1.120405  1.213698  1.194655  1.066666</code></pre>
<p>We can also try one with age squared, since the effect might not be linear (the age range is 11 to 68 which is quite a wide range). While we’re at it we’ll remove <code>sex</code> from the model since it appears to have no effect</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb242-1" tabindex="-1"></a>model2 <span class="ot">=</span> <span class="fu">glm</span>(status4 <span class="sc">~</span> centre <span class="sc">+</span> treatment <span class="sc">+</span> age <span class="sc">+</span> <span class="fu">I</span>(age<span class="sc">^</span>(<span class="dv">2</span>)) <span class="sc">+</span> status0, </span>
<span id="cb242-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb242-2" tabindex="-1"></a>             <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link=</span><span class="st">&#39;logit&#39;</span>), <span class="at">data=</span>resp_df)</span>
<span id="cb242-3"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb242-3" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = status4 ~ centre + treatment + age + I(age^(2)) + 
##     status0, family = binomial(link = &quot;logit&quot;), data = resp_df)
## 
## Coefficients:
##                     Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)         1.517788   1.512818   1.003 0.315723    
## centre2             1.268735   0.486975   2.605 0.009178 ** 
## treatmenttreatment  0.996219   0.465348   2.141 0.032290 *  
## age                -0.173598   0.087107  -1.993 0.046271 *  
## I(age^(2))          0.002000   0.001167   1.714 0.086530 .  
## status0good         1.671810   0.471304   3.547 0.000389 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 153.44  on 110  degrees of freedom
## Residual deviance: 116.44  on 105  degrees of freedom
## AIC: 128.44
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>This is an improvement in terms of AIC and deviance, so we’ll use this model (for now).</p>
</div>
</details>
<div class="exercise">
<p><span id="exr:unlabeled-div-109" class="exercise"><strong>Exercise D.2  </strong></span>Perform some diagnostics on the model you fitted in Exercise <a href="computer-practical-4---analysis-for-binary-and-survival-data.html#exr:lrresp1">D.1</a>, focussing on the model’s ability to discriminate between outcomes, and also on how well the model calibrates to the observed data.</p>
</div>
<details>
<summary>
Click for solution
</summary>
<div class="solution">
<p><span id="unlabeled-div-110" class="solution"><em>Solution</em>. </span>Firstly we’ll use ROC analysis to assess the model in terms of how well it discriminates the participants in terms of their respiratory status at 4 months.</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb244-1" tabindex="-1"></a><span class="fu">library</span>(pROC)</span>
<span id="cb244-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb244-2" tabindex="-1"></a>fit_resp <span class="ot">=</span> <span class="fu">fitted</span>(model2)   <span class="co"># Fitted values from model3</span></span>
<span id="cb244-3"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb244-3" tabindex="-1"></a>out_resp <span class="ot">=</span> resp_df<span class="sc">$</span>status4   <span class="co"># outcome values (1 or 2)</span></span>
<span id="cb244-4"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb244-4" tabindex="-1"></a>roc_resp_df <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">fit =</span> fit_resp, <span class="at">out =</span> out_resp)</span>
<span id="cb244-5"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb244-5" tabindex="-1"></a>roc_resp <span class="ot">=</span> <span class="fu">roc</span>(<span class="at">data=</span>roc_resp_df, <span class="at">response =</span> out, <span class="at">predictor=</span>fit)</span>
<span id="cb244-6"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb244-6" tabindex="-1"></a>roc_resp</span></code></pre></div>
<pre><code>## 
## Call:
## roc.data.frame(data = roc_resp_df, response = out, predictor = fit)
## 
## Data: fit in 52 controls (out poor) &lt; 59 cases (out good).
## Area under the curve: 0.8155</code></pre>
<p>The area under the curve (AUC) is around 0.8, which is generally considered quite good.</p>
<p>We can also plot the ROC curve</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb246-1" tabindex="-1"></a><span class="fu">ggroc</span>(roc_resp, <span class="at">legacy.axes=</span>T) <span class="sc">+</span> <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="dv">1</span>, <span class="at">intercept=</span><span class="dv">0</span>, <span class="at">type=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-162-1.png" width="672" /></p>
<p>Next we’ll assess the model in terms of calibration.</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-1" tabindex="-1"></a><span class="do">## Group the observations into age groups (I&#39;ve chosen 10 year bins)</span></span>
<span id="cb247-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-2" tabindex="-1"></a>resp_df<span class="sc">$</span>age10 <span class="ot">=</span> <span class="fu">round</span>(resp_df<span class="sc">$</span>age, <span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb247-3"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-3" tabindex="-1"></a><span class="co"># find mean status (minus 1 because factor levels are 1 and 2) and number of obs</span></span>
<span id="cb247-4"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-4" tabindex="-1"></a><span class="co"># for each combination of factor/age group levels</span></span>
<span id="cb247-5"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-5" tabindex="-1"></a>resp_sum <span class="ot">=</span> resp_df <span class="sc">%&gt;%</span> </span>
<span id="cb247-6"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-6" tabindex="-1"></a>  <span class="fu">group_by</span>(age10, centre, treatment, status0) <span class="sc">%&gt;%</span></span>
<span id="cb247-7"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-7" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb247-8"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-8" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(<span class="fu">as.numeric</span>(status4))<span class="sc">-</span><span class="dv">1</span>, </span>
<span id="cb247-9"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-9" tabindex="-1"></a>    <span class="at">n=</span><span class="fu">length</span>(age10), </span>
<span id="cb247-10"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-10" tabindex="-1"></a>    <span class="at">.groups=</span><span class="st">&quot;keep&quot;</span>)</span>
<span id="cb247-11"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-11" tabindex="-1"></a></span>
<span id="cb247-12"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-12" tabindex="-1"></a><span class="co"># Plot the observations, using facet_wrap to deal with two of the factors </span></span>
<span id="cb247-13"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-13" tabindex="-1"></a> </span>
<span id="cb247-14"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-14" tabindex="-1"></a>obs_plot <span class="ot">=</span> <span class="fu">ggplot</span>(<span class="at">data=</span>resp_sum, <span class="fu">aes</span>(<span class="at">x=</span>age10, <span class="at">col=</span>treatment)) <span class="sc">+</span></span>
<span id="cb247-15"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-15" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>mean, <span class="at">size=</span>n), <span class="at">pch=</span><span class="dv">16</span>) <span class="sc">+</span> </span>
<span id="cb247-16"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-16" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb247-17"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-17" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">c</span>(<span class="st">&quot;centre&quot;</span>, <span class="st">&quot;status0&quot;</span>)) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)</span>
<span id="cb247-18"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-18" tabindex="-1"></a></span>
<span id="cb247-19"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-19" tabindex="-1"></a><span class="do">## To include the estimate and SD from the model, we use the original dataset with continuous age,</span></span>
<span id="cb247-20"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-20" tabindex="-1"></a><span class="co"># fit model 2 including an estimate of SE, and use geom_line and geom_ribbon to add the fitted model with 95% intervals</span></span>
<span id="cb247-21"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-21" tabindex="-1"></a></span>
<span id="cb247-22"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-22" tabindex="-1"></a>fit_resp <span class="ot">=</span> <span class="fu">predict</span>(model2, <span class="at">newdata=</span>resp_df, <span class="at">se.fit=</span>T, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb247-23"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-23" tabindex="-1"></a></span>
<span id="cb247-24"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-24" tabindex="-1"></a>resp_df<span class="sc">$</span>fit <span class="ot">=</span> fit_resp<span class="sc">$</span>fit</span>
<span id="cb247-25"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-25" tabindex="-1"></a>resp_df<span class="sc">$</span>fit_se <span class="ot">=</span> fit_resp<span class="sc">$</span>se.fit</span>
<span id="cb247-26"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-26" tabindex="-1"></a></span>
<span id="cb247-27"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-27" tabindex="-1"></a>obs_plot <span class="sc">+</span> </span>
<span id="cb247-28"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-28" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data=</span>resp_df, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>fit)) <span class="sc">+</span></span>
<span id="cb247-29"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-29" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(</span>
<span id="cb247-30"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-30" tabindex="-1"></a>    <span class="at">data=</span>resp_df, </span>
<span id="cb247-31"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-31" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">ymin =</span> fit <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>fit_se, <span class="at">ymax =</span> fit <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>fit_se, <span class="at">fill =</span> treatment), </span>
<span id="cb247-32"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-32" tabindex="-1"></a>    <span class="at">alpha=</span><span class="fl">0.3</span></span>
<span id="cb247-33"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb247-33" tabindex="-1"></a>    )</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-163"></span>
<img src="CT4H_notes_files/figure-html/unnamed-chunk-163-1.png" alt="Observations and fitted model for combinations of centre (1: top and 2: bottom) for baseline status (poor: left and good: right)" width="672" />
<p class="caption">
Figure D.1: Observations and fitted model for combinations of centre (1: top and 2: bottom) for baseline status (poor: left and good: right)
</p>
</div>
<p>Overall, the model does not appear to be a great fit, but there is no systematic cause for concern.</p>
<p>These plots also give us an idea of the model’s fit for different categories of patient. For example, the probability of good respiratory symptoms at 4 months is much higher for a patient in the treatment group who had good symptoms at month zero, especially if they are young and belong to centre 2. The model’s output is much more bleak for a patient in group <span class="math inline">\(C\)</span> at centre 1 who had poor symptoms at month zero.</p>
</div>
</details>
<p>Having performed some diagnostics, we can proceed to use our model to provide information about the effect of the treatment to improve respiratory symptoms.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-111" class="exercise"><strong>Exercise D.3  </strong></span>Compute a 95% CI for the odd ratio for this trial, using the model you built in Exercise <a href="computer-practical-4---analysis-for-binary-and-survival-data.html#exr:lrresp1">D.1</a>.</p>
</div>
<details>
<summary>
Click for solution
</summary>
<div class="solution">
<p><span id="unlabeled-div-112" class="solution"><em>Solution</em>. </span>We can find the details of the coefficients via</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb248-1" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = status4 ~ centre + treatment + age + I(age^(2)) + 
##     status0, family = binomial(link = &quot;logit&quot;), data = resp_df)
## 
## Coefficients:
##                     Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)         1.517788   1.512818   1.003 0.315723    
## centre2             1.268735   0.486975   2.605 0.009178 ** 
## treatmenttreatment  0.996219   0.465348   2.141 0.032290 *  
## age                -0.173598   0.087107  -1.993 0.046271 *  
## I(age^(2))          0.002000   0.001167   1.714 0.086530 .  
## status0good         1.671810   0.471304   3.547 0.000389 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 153.44  on 110  degrees of freedom
## Residual deviance: 116.44  on 105  degrees of freedom
## AIC: 128.44
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>and find that the estimate of the log OR is 0.996, with an SE of 0.465, and therefore a 95% CI for the log OR is</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb250-1" tabindex="-1"></a>est_logOR <span class="ot">=</span> <span class="fu">summary</span>(model2)<span class="sc">$</span>coefficients[<span class="dv">3</span>,<span class="dv">1</span>]</span>
<span id="cb250-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb250-2" tabindex="-1"></a>se_logOR <span class="ot">=</span> <span class="fu">summary</span>(model2)<span class="sc">$</span>coefficients[<span class="dv">3</span>,<span class="dv">2</span>]</span>
<span id="cb250-3"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb250-3" tabindex="-1"></a>logOR_CI <span class="ot">=</span> <span class="fu">c</span>(est_logOR <span class="sc">-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)<span class="sc">*</span>se_logOR, est_logOR <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)<span class="sc">*</span>se_logOR)</span></code></pre></div>
<p>Finally we can use this to find a CI for the OR itself</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb251-1" tabindex="-1"></a><span class="fu">exp</span>(logOR_CI)</span></code></pre></div>
<pre><code>## [1] 1.087796 6.741514</code></pre>
<p>We call this the <strong>adjusted odds ratio</strong>, since we have adjusted for other covariates. Since this confidence interval does not contain the null value (1 for the OR), we see that the treatment effect is significant.</p>
<p>Note that these values are still quite difficult to interpret - this is an important issue in binary outcome RCTs in particular, as you’ll see in Formative 2.</p>
</div>
</details>
</div>
</div>
<div id="cp2-surv" class="section level2 hasAnchor" number="15.2">
<h2><span class="header-section-number">D.2</span> Analysis for Survival data<a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cp2-surv" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The packages we need for this section are <code>survival</code>, <code>ggsurvfit</code> and <code>survminer</code>, so load those now.</p>
<p>The first dataset we will use is <code>aml</code> - this dataset is from a trial investigating whether the standard course of chemotheraphy should be extended for some additional cycles (‘maintenance’) for patients with Acute Myelogenous Leukemia.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-113" class="exercise"><strong>Exercise D.4  </strong></span>Look at the help file for the <code>aml</code> dataset and make sure you understand what each variable is doing.
R might ask which <code>aml</code> dataset you want - if it does, choose the one from the <code>survival</code> package.</p>
</div>
<details>
<summary>
Click for solution
</summary>
<div class="solution">
<p><span id="unlabeled-div-114" class="solution"><em>Solution</em>. </span>The data set <code>aml</code> has three columns</p>
<ul>
<li><code>time</code> - survival or censoring time for each patient. This is the last time at which that patient was recorded.</li>
<li><code>status</code> - censoring status. By convention, this is 1 if a death is observed (ie. for complete data) and 0 for censored data (ie. the time in the <code>time</code> column was the last time that patient was seen, and they were still alive)</li>
<li><code>x</code> - maintenance chemotherapy given? This is the treatment variable</li>
</ul>
</div>
</details>
<p>The first step is to combine the first two columns into a form we can use. We do this using the <code>Surv</code> function in the package <code>survival</code>, which creates a ‘survival object’ that we can then use in various other functions. This object contains the times and the information about which observations are censored.</p>
<p>To create a survival object from some dataset <code>dataframe</code> containing a time variable and a censoring status variable, the general form is</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb253-1" tabindex="-1"></a>surv_obj <span class="ot">=</span> <span class="fu">with</span>(<span class="at">data=</span><span class="sc">&lt;</span>dataframe<span class="sc">&gt;</span>, <span class="fu">Surv</span>(<span class="sc">&lt;</span>time variable<span class="sc">&gt;</span>, <span class="sc">&lt;</span>censoring status variable<span class="sc">&gt;</span>))</span></code></pre></div>
<p>or if you prefer,</p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb254-1" tabindex="-1"></a>surv_obj <span class="ot">=</span> <span class="fu">Surv</span>(<span class="sc">&lt;</span>dataframe<span class="sc">$</span>time variable<span class="sc">&gt;</span>, <span class="sc">&lt;</span>dataframe<span class="sc">$</span>censoring status variable<span class="sc">&gt;</span>)</span></code></pre></div>
<div class="exercise">
<p><span id="exr:unlabeled-div-115" class="exercise"><strong>Exercise D.5  </strong></span>Use the <code>Surv</code> function now on the <code>aml</code> data. The output will contain some notation you probably haven’t seen before - can you work out what it means?</p>
</div>
<details>
<summary>
Click for solution
</summary>
<div class="solution">
<p><span id="unlabeled-div-116" class="solution"><em>Solution</em>. </span>We create the survival object for <code>aml</code> by</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb255-1" tabindex="-1"></a>surv_aml <span class="ot">=</span> <span class="fu">with</span>(<span class="at">data=</span>aml, <span class="fu">Surv</span>(time,status))</span>
<span id="cb255-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb255-2" tabindex="-1"></a>surv_aml</span></code></pre></div>
<pre><code>##  [1]   9   13   13+  18   23   28+  31   34   45+  48  161+   5    5    8    8   12   16+  23   27 
## [20]  30   33   43   45</code></pre>
<p>This is a vector of the time values, in the same order as in <code>aml</code>. You’ll notice that some have a ‘+’ attached. This denotes the censored observations (the notation reflects the fact that the true time of death/the event will be greater than this).</p>
</div>
</details>
<div id="fitting-a-survival-curve" class="section level3 hasAnchor" number="15.2.1">
<h3><span class="header-section-number">D.2.1</span> Fitting a survival curve<a href="computer-practical-4---analysis-for-binary-and-survival-data.html#fitting-a-survival-curve" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The next thing we probably want to do is to estimate the survival function and plot the survival curve.
The first method we’ll use is the Kaplan-Meier estimator.</p>
<div id="kaplan-meier" class="section level4 hasAnchor" number="15.2.1.1">
<h4><span class="header-section-number">D.2.1.1</span> Kaplan-Meier<a href="computer-practical-4---analysis-for-binary-and-survival-data.html#kaplan-meier" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To fit a Kaplan-Meier survival curve, we use the function <code>survfit</code>, which is specified using a formula, much like <code>lm</code> or <code>glm</code>. To fit a Kaplan-Meier estimate with a data frame split by treatment effect, the general form is</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb257-1" tabindex="-1"></a><span class="fu">survfit</span>(<span class="sc">&lt;</span>surv_obj<span class="sc">&gt;</span> <span class="er">~</span> <span class="er">&lt;</span>treatment var<span class="sc">&gt;</span>, <span class="at">data =</span> <span class="sc">&lt;</span>dataframe<span class="sc">&gt;</span>)</span></code></pre></div>
<p>We can then use <code>summary</code> to see the intermediary calculations at each step, and <code>plot</code> (for base plot) or <code>ggsurvfit</code> (from <code>ggplot2</code> and <code>ggsurvfit</code>) to plot the curves.</p>
<div class="exercise">
<p><span id="exr:kmaml" class="exercise"><strong>Exercise D.6  </strong></span>Fit a Kaplan-Meier estimator to the <code>aml</code> data. View the table using <code>summary</code>. Plot the curves.</p>
</div>
<details>
<summary>
Click for solution
</summary>
<div class="solution">
<p><span id="unlabeled-div-117" class="solution"><em>Solution</em>. </span>To fit the Kaplan-Meier estimator we use</p>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb258-1" tabindex="-1"></a>km_aml <span class="ot">=</span> <span class="fu">survfit</span>(surv_aml <span class="sc">~</span> x, <span class="at">data=</span>aml)</span></code></pre></div>
<p>We can then look at the summary table and plot the data by</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb259-1" tabindex="-1"></a><span class="fu">summary</span>(km_aml)</span></code></pre></div>
<pre><code>## Call: survfit(formula = surv_aml ~ x, data = aml)
## 
##                 x=Maintained 
##  time n.risk n.event survival std.err lower 95% CI upper 95% CI
##     9     11       1    0.909  0.0867       0.7541        1.000
##    13     10       1    0.818  0.1163       0.6192        1.000
##    18      8       1    0.716  0.1397       0.4884        1.000
##    23      7       1    0.614  0.1526       0.3769        0.999
##    31      5       1    0.491  0.1642       0.2549        0.946
##    34      4       1    0.368  0.1627       0.1549        0.875
##    48      2       1    0.184  0.1535       0.0359        0.944
## 
##                 x=Nonmaintained 
##  time n.risk n.event survival std.err lower 95% CI upper 95% CI
##     5     12       2   0.8333  0.1076       0.6470        1.000
##     8     10       2   0.6667  0.1361       0.4468        0.995
##    12      8       1   0.5833  0.1423       0.3616        0.941
##    23      6       1   0.4861  0.1481       0.2675        0.883
##    27      5       1   0.3889  0.1470       0.1854        0.816
##    30      4       1   0.2917  0.1387       0.1148        0.741
##    33      3       1   0.1944  0.1219       0.0569        0.664
##    43      2       1   0.0972  0.0919       0.0153        0.620
##    45      1       1   0.0000     NaN           NA           NA</code></pre>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb261-1" tabindex="-1"></a>km_aml <span class="sc">%&gt;%</span>  <span class="fu">ggsurvfit</span>() <span class="sc">+</span></span>
<span id="cb261-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb261-2" tabindex="-1"></a>  <span class="fu">add_censor_mark</span>() <span class="sc">+</span></span>
<span id="cb261-3"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb261-3" tabindex="-1"></a>  <span class="fu">add_risktable</span>() <span class="sc">+</span></span>
<span id="cb261-4"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb261-4" tabindex="-1"></a>  <span class="fu">add_confidence_interval</span>()</span></code></pre></div>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-172-1.png" width="672" /></p>
<p>We can see from the table that the lower curve is the non-maintained arm - there is only one survivor of this group, and the data finish at <span class="math inline">\(t=45\)</span>.</p>
</div>
</details>
<p>The function <code>add_risktable()</code> adds information about the numbers at risk and numbers of events. The function <code>add_confidence_interval()</code> adds a confidence interval, and we see that with the <code>aml</code> data the uncertainty is huge.</p>
</div>
<div id="fitting-an-exponential-distribution" class="section level4 hasAnchor" number="15.2.1.2">
<h4><span class="header-section-number">D.2.1.2</span> Fitting an exponential distribution<a href="computer-practical-4---analysis-for-binary-and-survival-data.html#fitting-an-exponential-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To fit an exponential distribution, we need to estimate <span class="math inline">\(\hat\lambda_C\)</span> and <span class="math inline">\(\hat\lambda_T\)</span>, using</p>
<p><span class="math display">\[\hat\lambda_X = \frac{m_X}{\sum\limits_{i=1}^{n_X} t_i} = \frac{m_X}{t^+_X}, \]</span>
where <span class="math inline">\(n_X\)</span> is the number of observations <span class="math inline">\(t_1,\ldots,t_{n_X}\)</span> in group <span class="math inline">\(X\)</span>, of which <span class="math inline">\(m_X\)</span> are censored.</p>
<div class="exercise">
<p><span id="exr:mlaml" class="exercise"><strong>Exercise D.7  </strong></span>Fit an exponential distribution for each treatment group to the <code>aml</code> data and plot the resulting estimated survival curves, along with the Kaplan Meier estimators from Exercise <a href="computer-practical-4---analysis-for-binary-and-survival-data.html#exr:kmaml">D.6</a> (for comparison).</p>
</div>
<details>
<summary>
Click for solution
</summary>
<div class="solution">
<p><span id="unlabeled-div-118" class="solution"><em>Solution</em>. </span>To calculate <span class="math inline">\(\hat\lambda_C\)</span> and <span class="math inline">\(\hat\lambda_T\)</span> we need to find <span class="math inline">\(m_C,\;\,m_T\;,t^+_C\)</span> and <span class="math inline">\(t^+_T\)</span>.</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb262-1" tabindex="-1"></a>mC_aml <span class="ot">=</span> <span class="fu">sum</span>((aml<span class="sc">$</span>status<span class="sc">==</span><span class="dv">1</span>)<span class="sc">&amp;</span>(aml<span class="sc">$</span>x<span class="sc">==</span><span class="st">&quot;Nonmaintained&quot;</span>))</span>
<span id="cb262-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb262-2" tabindex="-1"></a>mT_aml <span class="ot">=</span> <span class="fu">sum</span>((aml<span class="sc">$</span>status<span class="sc">==</span><span class="dv">1</span>)<span class="sc">&amp;</span>(aml<span class="sc">$</span>x<span class="sc">==</span><span class="st">&quot;Maintained&quot;</span>))</span>
<span id="cb262-3"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb262-3" tabindex="-1"></a>tsum_aml_C <span class="ot">=</span> <span class="fu">sum</span>(aml<span class="sc">$</span>time[aml<span class="sc">$</span>x<span class="sc">==</span><span class="st">&quot;Nonmaintained&quot;</span>])</span>
<span id="cb262-4"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb262-4" tabindex="-1"></a>tsum_aml_T <span class="ot">=</span> <span class="fu">sum</span>(aml<span class="sc">$</span>time[aml<span class="sc">$</span>x<span class="sc">==</span><span class="st">&quot;Maintained&quot;</span>])</span>
<span id="cb262-5"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb262-5" tabindex="-1"></a>lamhat_aml_C <span class="ot">=</span> mC_aml <span class="sc">/</span> tsum_aml_C</span>
<span id="cb262-6"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb262-6" tabindex="-1"></a>lamhat_aml_T <span class="ot">=</span> mT_aml <span class="sc">/</span> tsum_aml_T</span></code></pre></div>
<p>We can then plot the Survival curves using <code>geom_function</code></p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb263-1" tabindex="-1"></a><span class="co"># Define survival function for exponential density</span></span>
<span id="cb263-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb263-2" tabindex="-1"></a></span>
<span id="cb263-3"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb263-3" tabindex="-1"></a>exp_st <span class="ot">=</span> <span class="cf">function</span>(t, lambda){<span class="fu">exp</span>(<span class="sc">-</span>lambda<span class="sc">*</span>t)}</span>
<span id="cb263-4"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb263-4" tabindex="-1"></a></span>
<span id="cb263-5"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb263-5" tabindex="-1"></a>km_aml <span class="sc">%&gt;%</span> <span class="fu">ggsurvfit</span>() <span class="sc">+</span> <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">1</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb263-6"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb263-6" tabindex="-1"></a>  <span class="fu">add_censor_mark</span>() <span class="sc">+</span></span>
<span id="cb263-7"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb263-7" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun=</span>exp_st, <span class="at">args=</span><span class="fu">list</span>(<span class="at">lambda =</span> lamhat_aml_C), <span class="at">col=</span><span class="st">&quot;darkturquoise&quot;</span>) <span class="sc">+</span></span>
<span id="cb263-8"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb263-8" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun=</span>exp_st, <span class="at">args=</span><span class="fu">list</span>(<span class="at">lambda =</span> lamhat_aml_T), <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span></code></pre></div>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-174-1.png" width="672" /></p>
</div>
</details>
</div>
</div>
<div id="comparing-survival-curves-1" class="section level3 hasAnchor" number="15.2.2">
<h3><span class="header-section-number">D.2.2</span> Comparing survival curves<a href="computer-practical-4---analysis-for-binary-and-survival-data.html#comparing-survival-curves-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Having found the MLEs for the <code>aml</code> dataset, assuming an exponential distribution, we can now immediately conduct a likelihood ratio test.</p>
<div id="likelihood-ratio-test" class="section level4 hasAnchor" number="15.2.2.1">
<h4><span class="header-section-number">D.2.2.1</span> Likelihood ratio test<a href="computer-practical-4---analysis-for-binary-and-survival-data.html#likelihood-ratio-test" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Recall that our test statistic (which we found in Section <a href="comparing-survival-curves.html#survlrtest">8.1</a>) is</p>
<p><span class="math display">\[ \lambda_{LR} = 2\left(m_C\log\left(\frac{m_C}{t^+_C}\right) + m_T\log\left(\frac{m_T}{t^+_T}\right) - m\log\left(\frac{m}{t^+}\right)\right),\]</span></p>
<p>which we then refer to a <span class="math inline">\(\chi^2_1\)</span> distribution.</p>
<div class="exercise">
<p><span id="exr:lrtestaml" class="exercise"><strong>Exercise D.8  </strong></span>Conduct a likelihood ratio test for the <code>aml</code> data, with the null hypothesis that the survival curves are the same for both treatment groups. Before you calculate the answer, think about what you expect to see.</p>
</div>
<details>
<summary>
Click for solution
</summary>
<div class="solution">
<p><span id="unlabeled-div-119" class="solution"><em>Solution</em>. </span>We already have the <span class="math inline">\(m_X\)</span> and <span class="math inline">\(t^+_X\)</span> from Exercise <a href="computer-practical-4---analysis-for-binary-and-survival-data.html#exr:mlaml">D.7</a>, and we can easily find <span class="math inline">\(t^+\)</span> and <span class="math inline">\(m\)</span> from these.</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb264-1" tabindex="-1"></a>m_aml <span class="ot">=</span> mT_aml <span class="sc">+</span> mC_aml</span>
<span id="cb264-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb264-2" tabindex="-1"></a>tsum_aml <span class="ot">=</span> tsum_aml_T <span class="sc">+</span> tsum_aml_C</span></code></pre></div>
<p>and we can use these to compute <span class="math inline">\(\lambda_{LR}\)</span>:</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb265-1" tabindex="-1"></a>LRstat_aml <span class="ot">=</span>  <span class="dv">2</span><span class="sc">*</span>(mC_aml<span class="sc">*</span><span class="fu">log</span>(mC_aml<span class="sc">/</span>tsum_aml_C) <span class="sc">+</span> mT_aml<span class="sc">*</span><span class="fu">log</span>(mT_aml<span class="sc">/</span>tsum_aml_T) <span class="sc">-</span> m_aml<span class="sc">*</span><span class="fu">log</span>(m_aml<span class="sc">/</span>tsum_aml))</span>
<span id="cb265-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb265-2" tabindex="-1"></a>LRstat_aml</span></code></pre></div>
<pre><code>## [1] 4.061349</code></pre>
<p>Finally, we refer this to <span class="math inline">\(\chi^2_1\)</span></p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb267-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pchisq</span>(LRstat_aml, <span class="at">df=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 0.04387544</code></pre>
<p>We find that we have just enough evidence to reject <span class="math inline">\(H_0\)</span> at the 95% level.</p>
</div>
</details>
</div>
<div id="cp2logrank" class="section level4 hasAnchor" number="15.2.2.2">
<h4><span class="header-section-number">D.2.2.2</span> Log-rank test<a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cp2logrank" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><strong>Because our computer practicals are early in the week we haven’t covered this material yet in lectures. So, it might be sensible to return to it at a later date, and instead to continue to the extension question if you still have time in the session.</strong></p>
<p>The log-rank test is most easily found using the function <code>survdiff</code>. This function has an argument <code>rho</code> that controls the type of test. If we set <code>rho=0</code> then it performs a log-rank test.</p>
<p>The general form is similar to <code>survfit</code>:</p>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb269-1" tabindex="-1"></a><span class="fu">survdiff</span>(<span class="sc">&lt;</span>surv_obj<span class="sc">&gt;</span> <span class="er">~</span> <span class="er">&lt;</span>treatment variable<span class="sc">&gt;</span>, <span class="at">data=</span><span class="sc">&lt;</span>dataframe<span class="sc">&gt;</span>, <span class="at">rho=</span><span class="dv">0</span>)</span></code></pre></div>
<div class="exercise">
<p><span id="exr:logrankaml" class="exercise"><strong>Exercise D.9  </strong></span>Use <code>survdiff</code> to do a log rank test on the <code>aml</code> data. Do you expect the results to be similar to your results from Exercise <a href="computer-practical-4---analysis-for-binary-and-survival-data.html#exr:lrtestaml">D.8</a>?</p>
</div>
<details>
<summary>
Click for solution
</summary>
<div class="solution">
<p><span id="unlabeled-div-120" class="solution"><em>Solution</em>. </span>To conduct a log rank test we use</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb270-1" tabindex="-1"></a><span class="fu">survdiff</span>(surv_aml<span class="sc">~</span>x, <span class="at">data=</span>aml, <span class="at">rho=</span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## Call:
## survdiff(formula = surv_aml ~ x, data = aml, rho = 0)
## 
##                  N Observed Expected (O-E)^2/E (O-E)^2/V
## x=Maintained    11        7    10.69      1.27       3.4
## x=Nonmaintained 12       11     7.31      1.86       3.4
## 
##  Chisq= 3.4  on 1 degrees of freedom, p= 0.07</code></pre>
<p>This is not that close to the result of the likelihood ratio test, probably reflecting the less-than-perfect fit of the exponential survival curve.</p>
</div>
</details>
</div>
<div id="cox-regression" class="section level4 hasAnchor" number="15.2.2.3">
<h4><span class="header-section-number">D.2.2.3</span> Cox regression<a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cox-regression" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Finally, we will fit the Cox regression model. This is done using the function <code>coxph</code> in the package <code>survival</code>. Look at the help file and the examples in Section <a href="comparing-survival-curves.html#coxreg">8.3.2</a> to understand how to use this function.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-121" class="exercise"><strong>Exercise D.10  </strong></span>Fit a Cox proportional hazards model to the data. Do you think this is an appropriate model to use? How influential is the treatment?</p>
</div>
<details>
<summary>
Click for solution
</summary>
<div class="solution">
<p><span id="unlabeled-div-122" class="solution"><em>Solution</em>. </span>In the <code>aml</code> dataset there are no baseline covariates, so our only dependent variable is the treatment group variable <code>x</code>.</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb272-1" tabindex="-1"></a>cox_aml <span class="ot">=</span> <span class="fu">coxph</span>(<span class="at">formula =</span> <span class="fu">Surv</span>(time, status)<span class="sc">~</span>x, <span class="at">data=</span>aml)</span>
<span id="cb272-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb272-2" tabindex="-1"></a>cox_aml</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(time, status) ~ x, data = aml)
## 
##                  coef exp(coef) se(coef)     z      p
## xNonmaintained 0.9155    2.4981   0.5119 1.788 0.0737
## 
## Likelihood ratio test=3.38  on 1 df, p=0.06581
## n= 23, number of events= 18</code></pre>
<p>We’ve already seen that the survival curves don’t cross, so we can be reasonably comfortable fitting this model. To see how the model performs, we can use the summary function:</p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb274-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb274-1" tabindex="-1"></a><span class="fu">summary</span>(cox_aml)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(time, status) ~ x, data = aml)
## 
##   n= 23, number of events= 18 
## 
##                  coef exp(coef) se(coef)     z Pr(&gt;|z|)  
## xNonmaintained 0.9155    2.4981   0.5119 1.788   0.0737 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##                exp(coef) exp(-coef) lower .95 upper .95
## xNonmaintained     2.498     0.4003    0.9159     6.813
## 
## Concordance= 0.619  (se = 0.063 )
## Likelihood ratio test= 3.38  on 1 df,   p=0.07
## Wald test            = 3.2  on 1 df,   p=0.07
## Score (logrank) test = 3.42  on 1 df,   p=0.06</code></pre>
<p>To check this more carefully we can use the log-log plot</p>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-182-1.png" width="672" /></p>
<p>and we see that the curves are close to parallel.</p>
<p>Although the coefficient of <code>x</code> isn’t quite significant at the 0.05 level, it appears there is reasonable evidence that the treatment has an effect (though probably not enough to make a clinical decision).</p>
</div>
</details>
<div class="exercise">
<p><span id="exr:unlabeled-div-123" class="exercise"><strong>Exercise D.11  </strong></span>The dataset <code>colon</code>, also from the <code>survival</code> package, contains data from a trial of colon cancer patients, comparing three treatments: observation (<code>obs</code>), levamisole (<code>Lev</code>) and levamisole + 5-FU (<code>Lev+5FU</code>). To simplify things, we will restrict the data to those patients on <code>Obs</code> or <code>Lev+5FU</code>. The main report of this trial is <span class="citation">Moertel et al. (<a href="#ref-moertel1990levamisole">1990</a>)</span>.</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb276-1" tabindex="-1"></a>colondf <span class="ot">=</span> colon[colon<span class="sc">$</span>rx<span class="sc">!=</span><span class="st">&quot;Lev&quot;</span>,]</span>
<span id="cb276-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb276-2" tabindex="-1"></a>colondf<span class="sc">$</span>rx <span class="ot">=</span> <span class="fu">as.factor</span>(<span class="fu">as.character</span>(colondf<span class="sc">$</span>rx)) <span class="co"># Removes Lev factor level</span></span></code></pre></div>
<p>For this data</p>
<ol style="list-style-type: decimal">
<li>Look at the help file and make sure you understand what the columns mean</li>
<li>Fit Kaplan-Meier estimators to the survival curves for the two groups.</li>
<li>Perform some tests to see whether the treatment has a significant effect on the outcome. What do you find?</li>
</ol>
</div>
<details>
<summary>
Click for solution
</summary>
<div class="solution">
<p><span id="unlabeled-div-124" class="solution"><em>Solution</em>. </span>From the help file we see that <code>rx</code> is the treatment group, <code>stop</code> is the time variable, <code>status</code> gives the censoring status.</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb277-1" tabindex="-1"></a><span class="fu">str</span>(colondf)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    1238 obs. of  16 variables:
##  $ id      : num  1 1 2 2 3 3 4 4 5 5 ...
##  $ study   : num  1 1 1 1 1 1 1 1 1 1 ...
##  $ rx      : Factor w/ 2 levels &quot;Lev+5FU&quot;,&quot;Obs&quot;: 1 1 1 1 2 2 1 1 2 2 ...
##  $ sex     : num  1 1 1 1 0 0 0 0 1 1 ...
##  $ age     : num  43 43 63 63 71 71 66 66 69 69 ...
##  $ obstruct: num  0 0 0 0 0 0 1 1 0 0 ...
##  $ perfor  : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ adhere  : num  0 0 0 0 1 1 0 0 0 0 ...
##  $ nodes   : num  5 5 1 1 7 7 6 6 22 22 ...
##  $ status  : num  1 1 0 0 1 1 1 1 1 1 ...
##  $ differ  : num  2 2 2 2 2 2 2 2 2 2 ...
##  $ extent  : num  3 3 3 3 2 2 3 3 3 3 ...
##  $ surg    : num  0 0 0 0 0 0 1 1 1 1 ...
##  $ node4   : num  1 1 0 0 1 1 1 1 1 1 ...
##  $ time    : num  1521 968 3087 3087 963 ...
##  $ etype   : num  2 1 2 1 2 1 2 1 2 1 ...</code></pre>
<p>We can therefore fit (and plot) the Kaplan-Meier estimator split by treatment group.</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb279-1" tabindex="-1"></a>km_colon <span class="ot">=</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> rx, <span class="at">data=</span>colondf)</span>
<span id="cb279-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb279-2" tabindex="-1"></a>km_colon <span class="sc">%&gt;%</span> ggsurvfit <span class="sc">+</span> <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb279-3"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb279-3" tabindex="-1"></a>  <span class="fu">add_censor_mark</span>() <span class="sc">+</span></span>
<span id="cb279-4"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb279-4" tabindex="-1"></a>  <span class="fu">add_confidence_interval</span>()</span></code></pre></div>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-185-1.png" width="672" /></p>
<p>Next we can find the MLE for each treatment group</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb280-1" tabindex="-1"></a>mC_colon <span class="ot">=</span> <span class="fu">sum</span>((colondf<span class="sc">$</span>status<span class="sc">==</span><span class="dv">1</span>)<span class="sc">&amp;</span>(colondf<span class="sc">$</span>rx<span class="sc">==</span><span class="st">&quot;Obs&quot;</span>))</span>
<span id="cb280-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb280-2" tabindex="-1"></a>mT_colon <span class="ot">=</span> <span class="fu">sum</span>((colondf<span class="sc">$</span>status<span class="sc">==</span><span class="dv">1</span>)<span class="sc">&amp;</span>(colondf<span class="sc">$</span>rx<span class="sc">==</span><span class="st">&quot;Lev+5FU&quot;</span>))</span>
<span id="cb280-3"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb280-3" tabindex="-1"></a>tsum_colon_C <span class="ot">=</span> <span class="fu">sum</span>(colondf<span class="sc">$</span>time[colondf<span class="sc">$</span>rx<span class="sc">==</span><span class="st">&quot;Obs&quot;</span>])</span>
<span id="cb280-4"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb280-4" tabindex="-1"></a>tsum_colon_T <span class="ot">=</span> <span class="fu">sum</span>(colondf<span class="sc">$</span>time[colondf<span class="sc">$</span>rx<span class="sc">==</span><span class="st">&quot;Lev+5FU&quot;</span>])</span>
<span id="cb280-5"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb280-5" tabindex="-1"></a>lamhat_colon_C <span class="ot">=</span> mC_colon <span class="sc">/</span> tsum_colon_C</span>
<span id="cb280-6"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb280-6" tabindex="-1"></a>lamhat_colon_T <span class="ot">=</span> mT_colon <span class="sc">/</span> tsum_colon_T</span></code></pre></div>
<p>We can then plot the Survival curves using <code>geom_function</code></p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb281-1" tabindex="-1"></a><span class="co"># Define survival function for exponential density</span></span>
<span id="cb281-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb281-2" tabindex="-1"></a></span>
<span id="cb281-3"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb281-3" tabindex="-1"></a>km_colon <span class="sc">%&gt;%</span> <span class="fu">ggsurvfit</span>() <span class="sc">+</span></span>
<span id="cb281-4"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb281-4" tabindex="-1"></a>    <span class="fu">add_censor_mark</span>() <span class="sc">+</span></span>
<span id="cb281-5"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb281-5" tabindex="-1"></a>  <span class="fu">add_risktable</span>() <span class="sc">+</span></span>
<span id="cb281-6"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb281-6" tabindex="-1"></a>  <span class="fu">add_confidence_interval</span>() <span class="sc">+</span> </span>
<span id="cb281-7"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb281-7" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">1</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb281-8"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb281-8" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun=</span>exp_st, <span class="at">args=</span><span class="fu">list</span>(<span class="at">lambda =</span> lamhat_colon_C), <span class="at">col=</span><span class="st">&quot;darkturquoise&quot;</span>) <span class="sc">+</span></span>
<span id="cb281-9"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb281-9" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun=</span>exp_st, <span class="at">args=</span><span class="fu">list</span>(<span class="at">lambda =</span> lamhat_colon_T), <span class="at">col=</span><span class="st">&quot;red&quot;</span>) </span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:cp2poorfit"></span>
<img src="CT4H_notes_files/figure-html/cp2poorfit-1.png" alt="Survival curves for groups C and T in colon study, fitted assuming an exponential distribution. Kaplan-Meier estimates also shown." width="672" />
<p class="caption">
Figure D.2: Survival curves for groups C and T in colon study, fitted assuming an exponential distribution. Kaplan-Meier estimates also shown.
</p>
</div>
<p>We see that this fit is quite poor.</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb282-1" tabindex="-1"></a>m_colon <span class="ot">=</span> mT_colon <span class="sc">+</span> mC_colon</span>
<span id="cb282-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb282-2" tabindex="-1"></a>tsum_colon <span class="ot">=</span> tsum_colon_T <span class="sc">+</span> tsum_colon_C</span></code></pre></div>
<p>and we can use these to compute <span class="math inline">\(\lambda_{LR}\)</span>:</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb283-1" tabindex="-1"></a>LRstat_colon <span class="ot">=</span>  <span class="dv">2</span><span class="sc">*</span>(mC_colon<span class="sc">*</span><span class="fu">log</span>(mC_colon<span class="sc">/</span>tsum_colon_C) <span class="sc">+</span> mT_colon<span class="sc">*</span><span class="fu">log</span>(mT_colon<span class="sc">/</span>tsum_colon_T) <span class="sc">-</span> m_colon<span class="sc">*</span><span class="fu">log</span>(m_colon<span class="sc">/</span>tsum_colon))</span>
<span id="cb283-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb283-2" tabindex="-1"></a>LRstat_colon</span></code></pre></div>
<pre><code>## [1] 35.0111</code></pre>
<p>Finally, we refer this to <span class="math inline">\(\chi^2_1\)</span></p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb285-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pchisq</span>(LRstat_colon, <span class="at">df=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 3.278309e-09</code></pre>
<p>Highly significant, but because of the very poor fit in Figure <a href="computer-practical-4---analysis-for-binary-and-survival-data.html#fig:cp2poorfit">D.2</a> not especially trustworthy.</p>
<p>Next, we can perform a log-rank test:</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb287-1" tabindex="-1"></a><span class="fu">survdiff</span>(<span class="fu">Surv</span>(time, status)<span class="sc">~</span>rx, <span class="at">data=</span>colondf, <span class="at">rho=</span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## Call:
## survdiff(formula = Surv(time, status) ~ rx, data = colondf, rho = 0)
## 
##              N Observed Expected (O-E)^2/E (O-E)^2/V
## rx=Lev+5FU 608      242      306      13.5      28.2
## rx=Obs     630      345      281      14.7      28.2
## 
##  Chisq= 28.2  on 1 degrees of freedom, p= 1e-07</code></pre>
<p>We see that the test statistic, although still very significant, is much lower than for the likelihood ratio test.</p>
<p>Finally, we fit a Cox regression model. In the first instance we can do this with just the treatment group as a covariate:</p>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb289-1" tabindex="-1"></a><span class="fu">coxph</span>(<span class="at">formula =</span> <span class="fu">Surv</span>(time, status)<span class="sc">~</span>rx, <span class="at">data=</span>colondf)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(time, status) ~ rx, data = colondf)
## 
##          coef exp(coef) se(coef)     z        p
## rxObs 0.44213   1.55602  0.08394 5.267 1.38e-07
## 
## Likelihood ratio test=28.25  on 1 df, p=1.068e-07
## n= 1238, number of events= 587</code></pre>
<p>But we can also include other baseline covariates</p>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb291-1" tabindex="-1"></a><span class="fu">coxph</span>(<span class="at">formula =</span> <span class="fu">Surv</span>(time, status)<span class="sc">~</span>rx <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> obstruct <span class="sc">+</span> nodes, <span class="at">data=</span>colondf)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(time, status) ~ rx + sex + age + obstruct + 
##     nodes, data = colondf)
## 
##               coef exp(coef)  se(coef)      z        p
## rxObs     0.470039  1.600056  0.085522  5.496 3.88e-08
## sex      -0.155126  0.856308  0.083835 -1.850   0.0643
## age      -0.002940  0.997064  0.003400 -0.865   0.3872
## obstruct  0.072027  1.074685  0.105813  0.681   0.4961
## nodes     0.104607  1.110274  0.008493 12.317  &lt; 2e-16
## 
## Likelihood ratio test=146  on 5 df, p=&lt; 2.2e-16
## n= 1214, number of events= 574 
##    (24 observations deleted due to missingness)</code></pre>
<p>and we see that as well as the treatment arm, the number of lymph nodes with detectable cancer (given by <code>nodes</code>) is highly significant, and <code>sex</code> is also close to significant.</p>
<p>We can visualise this by further subsetting the Kaplan-Meier estimator</p>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb293-1" tabindex="-1"></a>km_colon_bl <span class="ot">=</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> rx <span class="sc">+</span> sex, <span class="at">data=</span>colondf)</span>
<span id="cb293-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb293-2" tabindex="-1"></a>km_colon_bl <span class="sc">%&gt;%</span> <span class="fu">ggsurvfit</span>() <span class="sc">+</span></span>
<span id="cb293-3"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb293-3" tabindex="-1"></a>  <span class="fu">add_censor_mark</span>() </span></code></pre></div>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-193-1.png" width="672" /></p>
<p><code>nodes</code> is a numeric output, so one way to get a visual impression of its effect on the survival curve is to bin it. For example, we can choose <span class="math inline">\(\texttt{nodes}\leq 4\)</span> and <span class="math inline">\(\texttt{nodes}&gt;4\)</span>.</p>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb294-1" tabindex="-1"></a>colondf<span class="sc">$</span>nodes4 <span class="ot">=</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(colondf), <span class="cf">function</span>(i){<span class="fu">ifelse</span>(colondf<span class="sc">$</span>nodes[i]<span class="sc">&gt;</span><span class="dv">4</span>, <span class="dv">1</span>, <span class="dv">0</span>)})</span>
<span id="cb294-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb294-2" tabindex="-1"></a>km_colon_bl <span class="ot">=</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> rx <span class="sc">+</span> nodes4, <span class="at">data=</span>colondf)</span>
<span id="cb294-3"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb294-3" tabindex="-1"></a>km_colon_bl <span class="sc">%&gt;%</span> <span class="fu">ggsurvfit</span>()</span></code></pre></div>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-194-1.png" width="672" /></p>
<p>The separation in the lines fits with the strong effect of <code>nodes</code> in the model.</p>
<p>To check our model more carefully we can use the log-log plot for the categorical variables:</p>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb295-1" tabindex="-1"></a>km_colon <span class="ot">=</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> rx <span class="sc">+</span> sex, <span class="at">data=</span>colondf)</span>
<span id="cb295-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb295-2" tabindex="-1"></a><span class="fu">ggsurvplot</span>(km_colon, <span class="at">fun =</span> <span class="st">&quot;cloglog&quot;</span>)</span></code></pre></div>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-195-1.png" width="672" /></p>
<p>and the Schoenfeld residuals for the continuous residuals (after removing the insignificant variables):</p>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb296-1" tabindex="-1"></a>cox_colon <span class="ot">=</span> <span class="fu">coxph</span>(<span class="at">formula =</span> <span class="fu">Surv</span>(time, status)<span class="sc">~</span>rx <span class="sc">+</span> sex <span class="sc">+</span> nodes, <span class="at">data=</span>colondf)</span>
<span id="cb296-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb296-2" tabindex="-1"></a></span>
<span id="cb296-3"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb296-3" tabindex="-1"></a><span class="fu">ggcoxzph</span>(<span class="fu">cox.zph</span>(cox_colon), <span class="at">var =</span> <span class="st">&quot;nodes&quot;</span>)</span></code></pre></div>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-196-1.png" width="672" /></p>
<p>and we see that there is insufficient evidence to reject the null hypothesis (of proportional hazards).</p>
</div>
</details>
</div>
</div>
</div>
<div id="cp4sim2" class="section level2 hasAnchor" number="15.3">
<h2><span class="header-section-number">D.3</span> Extension problem: sample size by simulation (part II)<a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cp4sim2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We now combine the work we’ve done, to implement power simulation for a survival outcome trial.</p>
<p>To simulate survival / time-to-event data as though from a clinical trial, we need to consider two things:</p>
<ol style="list-style-type: decimal">
<li>The distribution of the observation/event times (if everyone were observed perfectly)</li>
<li>The censoring mechanism</li>
</ol>
<p>For the first, we are likely to use a probability distribution like the exponential (which we saw in Section <a href="working-with-time-to-event-data.html#surv-exp">7.2.2</a>) or the Weibull (which we looked at briefly in Section <a href="working-with-time-to-event-data.html#weibull">7.2.3</a>).</p>
<p>For the second, there are two aspects:</p>
<ol style="list-style-type: decimal">
<li>Anyone who is still alive (or hasn’t experienced the event) by the end of the trial will be censored at that point</li>
<li>There will be some censoring during the lifetime of the trial, and this should also be randomly generated.</li>
</ol>
<p>In this practical we’ll use an Exponential distribution. If you want to read more about this approach, you can read <span class="citation">Jiang et al. (<a href="#ref-jiang2012practical">2012</a>)</span>, who use a Weibull distribution.</p>
<div id="minimum-detectable-effect-size" class="section level3 hasAnchor" number="15.3.1">
<h3><span class="header-section-number">D.3.1</span> Minimum detectable effect size<a href="computer-practical-4---analysis-for-binary-and-survival-data.html#minimum-detectable-effect-size" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>One of the first practical issues we need to tackle is the concept of the difference between the treatment and control group outcomes, and the idea of the minimum difference we want to be able to detect. Ideally this should be something clinically meaningful. We also need to work out how to factor this into the simulation.</p>
<p>Adapting the approach followed by <span class="citation">Jiang et al. (<a href="#ref-jiang2012practical">2012</a>)</span>, our steps will be:</p>
<ol style="list-style-type: decimal">
<li>Specify the median survival time for the control and treatment groups, <span class="math inline">\(M_C\)</span> and <span class="math inline">\(M_T\)</span>. We’re assuming that ‘the event’ is bad, and so we’ll assume <span class="math inline">\(M_T&gt;M_C\)</span>. This is how the MDES concept enters the simulation, so <span class="math inline">\(M_T\)</span> should be the smallest value of <span class="math inline">\(M_T\)</span> we want to be able to detect (ie. creating the smallest clinically worthwhile improvement from <span class="math inline">\(M_C\)</span>, which we assume to be well understood).</li>
<li>Use <span class="math inline">\(M_C,\,M_T\)</span> to find the parameters <span class="math inline">\(\lambda_C,\,\lambda_T\)</span>, which then give us our observation time distribution function for each group.</li>
</ol>
</div>
<div id="censoring" class="section level3 hasAnchor" number="15.3.2">
<h3><span class="header-section-number">D.3.2</span> Censoring<a href="computer-practical-4---analysis-for-binary-and-survival-data.html#censoring" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Censoring will happen in two ways:</p>
<ol style="list-style-type: decimal">
<li>An endpoint <span class="math inline">\(T_{max}\)</span> is specified as part of the trial design, and any observation after <span class="math inline">\(T_{max}\)</span> is censored at <span class="math inline">\(T_{max}\)</span></li>
<li>Every simulation is censored with a specified drop-out probability <span class="math inline">\(\pi\)</span>, using a Bernoulli distribution. The value of the censored observation is kept at the value simulated from the exponential distribution.</li>
</ol>
<p>There are other ways to model drop-out, but this relatively simple method works nicely.</p>
<div class="exercise">
<p><span id="exr:survsim1" class="exercise"><strong>Exercise D.12  </strong></span>Write code to simulate a survival trial dataset as described above. Using this function, simulate data for a trial where <span class="math inline">\(M_T=7,\,M_C=5,\,\pi=0.1, t_{max}=10\)</span>, with approximately 100 participants in each group.</p>
<ul>
<li>Plot the Kaplan-Meier estimated survival curve of your data</li>
<li>What are some of the modelling assumptions/simplifications that have been made?</li>
</ul>
<p>Some technical things to note:</p>
<ul>
<li>For the <code>Surv</code> function to interpret the time and status as right censored, it seems that the status variable has to be numeric (not factor, which would seem more logical)</li>
</ul>
<details>
<summary>
<em>Click for hint 1 (about finding <span class="math inline">\(\lambda_C,\,\lambda_T\)</span>)</em>
</summary>
<p>The CDF of the exponential distribution is</p>
<p><span class="math display">\[ P\left(X \leq x\right) = 1 - e^{-\lambda x}.\]</span>
You can find the median value of <span class="math inline">\(x\)</span> by setting the CDF to 0.5, which gives a median value of</p>
<p><span class="math display">\[\frac{\ln{2}}{\lambda}.\]</span></p>
</details>
<details>
<summary>
<em>Click for hint 2 (about setting up the simulated data)</em>
</summary>
<p>Your simulated participant data frame should have three columns (they don’t need to have these exact names):</p>
<ul>
<li>Time</li>
<li>Status (censored = 0, complete = 1)</li>
<li>Group (Control or Treatment)</li>
</ul>
</details>
</div>
<details>
<summary>
Click for solution
</summary>
<div class="solution">
<p><span id="unlabeled-div-125" class="solution"><em>Solution</em>. </span>As we did in Section <a href="cp3sim.html#cp3sim">C</a> we’ll write functions so that we can do all of this lots of times.
Firstly, we rearrange the median equation in the hint above to find the <span class="math inline">\(\lambda_T,\,\lambda_C\)</span>:</p>
<p><span class="math display">\[\lambda_X = \frac{\ln2}{M_X},\]</span>
where <span class="math inline">\(X\)</span> is <span class="math inline">\(C\)</span> or <span class="math inline">\(T\)</span>.</p>
<p>Therefore we have <span class="math inline">\(\lambda_C = 0.139,\,\lambda_T = 0.099\)</span>.</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-1" tabindex="-1"></a><span class="do">## THIS IS DEFNITELY NOT GIVING THE RIGHT DATA!</span></span>
<span id="cb297-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-2" tabindex="-1"></a>surv_data <span class="ot">=</span> <span class="cf">function</span>(</span>
<span id="cb297-3"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-3" tabindex="-1"></a>    npart, <span class="co"># number of participants per group (roughly)</span></span>
<span id="cb297-4"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-4" tabindex="-1"></a>    MC,    <span class="co"># median survival time - group C</span></span>
<span id="cb297-5"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-5" tabindex="-1"></a>    MT,    <span class="co"># median survival time.- group T</span></span>
<span id="cb297-6"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-6" tabindex="-1"></a>    p_cens, <span class="co"># probability of censoring for each observation</span></span>
<span id="cb297-7"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-7" tabindex="-1"></a>    t_max   <span class="co"># end point of trial</span></span>
<span id="cb297-8"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-8" tabindex="-1"></a>){</span>
<span id="cb297-9"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-9" tabindex="-1"></a>  rateC <span class="ot">=</span> <span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span>(MC)</span>
<span id="cb297-10"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-10" tabindex="-1"></a>  rateT <span class="ot">=</span> <span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span>(MT)</span>
<span id="cb297-11"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-11" tabindex="-1"></a></span>
<span id="cb297-12"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-12" tabindex="-1"></a>  dat_mat <span class="ot">=</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow=</span><span class="dv">2</span><span class="sc">*</span>npart, <span class="at">ncol=</span><span class="dv">3</span>)</span>
<span id="cb297-13"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-13" tabindex="-1"></a>  dat_df <span class="ot">=</span> <span class="fu">as.data.frame</span>(dat_mat)</span>
<span id="cb297-14"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-14" tabindex="-1"></a>  <span class="fu">names</span>(dat_df) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;time&quot;</span>, <span class="st">&quot;status&quot;</span>, <span class="st">&quot;group&quot;</span>)</span>
<span id="cb297-15"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-15" tabindex="-1"></a>  </span>
<span id="cb297-16"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-16" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span>npart)){</span>
<span id="cb297-17"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-17" tabindex="-1"></a>    <span class="co"># Using SRS here, but could use something else</span></span>
<span id="cb297-18"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-18" tabindex="-1"></a>    group_i <span class="ot">=</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">&quot;C&quot;</span>, <span class="st">&quot;T&quot;</span>), <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb297-19"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-19" tabindex="-1"></a>    <span class="co"># Generate time accordingly</span></span>
<span id="cb297-20"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-20" tabindex="-1"></a>    <span class="cf">if</span> (group_i <span class="sc">==</span> <span class="st">&quot;C&quot;</span>){</span>
<span id="cb297-21"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-21" tabindex="-1"></a>      time_i <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">rexp</span>(<span class="dv">1</span>, <span class="at">rate =</span> rateC))</span>
<span id="cb297-22"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-22" tabindex="-1"></a>    } <span class="cf">else</span> <span class="cf">if</span> (group_i <span class="sc">==</span> <span class="st">&quot;T&quot;</span>){</span>
<span id="cb297-23"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-23" tabindex="-1"></a>      time_i <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">rexp</span>(<span class="dv">1</span>, <span class="at">rate =</span> rateT))</span>
<span id="cb297-24"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-24" tabindex="-1"></a>    }</span>
<span id="cb297-25"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-25" tabindex="-1"></a>    <span class="co"># Determine whether observation i is censored</span></span>
<span id="cb297-26"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-26" tabindex="-1"></a>    status_i <span class="ot">=</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">size=</span><span class="dv">1</span>, <span class="at">prob =</span> <span class="fu">c</span>(p_cens, <span class="dv">1</span><span class="sc">-</span>p_cens))</span>
<span id="cb297-27"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-27" tabindex="-1"></a>    <span class="cf">if</span>(time_i<span class="sc">&gt;</span>t_max){</span>
<span id="cb297-28"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-28" tabindex="-1"></a>      time_i <span class="ot">=</span> t_max</span>
<span id="cb297-29"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-29" tabindex="-1"></a>      status_i <span class="ot">=</span> <span class="dv">0</span></span>
<span id="cb297-30"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-30" tabindex="-1"></a>    }</span>
<span id="cb297-31"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-31" tabindex="-1"></a>    <span class="co"># Having a zero time observation messes things up so we fudge it slightly</span></span>
<span id="cb297-32"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-32" tabindex="-1"></a>    <span class="cf">if</span>(time_i <span class="sc">==</span> <span class="dv">0</span>){</span>
<span id="cb297-33"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-33" tabindex="-1"></a>      time_i <span class="ot">=</span> <span class="dv">1</span></span>
<span id="cb297-34"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-34" tabindex="-1"></a>      status_i <span class="ot">=</span> <span class="dv">1</span></span>
<span id="cb297-35"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-35" tabindex="-1"></a>    }</span>
<span id="cb297-36"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-36" tabindex="-1"></a>    </span>
<span id="cb297-37"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-37" tabindex="-1"></a>    dat_df[i,] <span class="ot">=</span> <span class="fu">c</span>(time_i, status_i, group_i)</span>
<span id="cb297-38"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-38" tabindex="-1"></a>  }</span>
<span id="cb297-39"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-39" tabindex="-1"></a>  <span class="co"># Round to 0 dp for a hint of reality</span></span>
<span id="cb297-40"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-40" tabindex="-1"></a>  dat_df<span class="sc">$</span>time <span class="ot">=</span> <span class="fu">as.numeric</span>(dat_df<span class="sc">$</span>time)</span>
<span id="cb297-41"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-41" tabindex="-1"></a>  dat_df<span class="sc">$</span>status <span class="ot">=</span> <span class="fu">as.numeric</span>(dat_df<span class="sc">$</span>status)</span>
<span id="cb297-42"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-42" tabindex="-1"></a>  dat_df<span class="sc">$</span>group <span class="ot">=</span> <span class="fu">as.factor</span>(dat_df<span class="sc">$</span>group)</span>
<span id="cb297-43"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-43" tabindex="-1"></a>  </span>
<span id="cb297-44"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-44" tabindex="-1"></a>  <span class="fu">return</span>(dat_df)</span>
<span id="cb297-45"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb297-45" tabindex="-1"></a>}</span></code></pre></div>
<p>We can use the function to simulate the data described above</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb298-1" tabindex="-1"></a>surv_df1 <span class="ot">=</span> <span class="fu">surv_data</span>(<span class="at">npart=</span><span class="dv">100</span>, <span class="at">MC=</span><span class="dv">5</span>, <span class="at">MT=</span><span class="dv">7</span>, <span class="at">p_cens=</span><span class="fl">0.1</span>, <span class="at">t_max=</span><span class="dv">10</span>)</span>
<span id="cb298-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb298-2" tabindex="-1"></a><span class="fu">with</span>(<span class="at">data =</span> surv_df1, <span class="fu">Surv</span>(time, status, <span class="at">type =</span> <span class="st">&quot;right&quot;</span>))</span></code></pre></div>
<pre><code>##   [1]  3   1  10+  3   1  10  10+ 10+ 10+  6   9   6+  3   2   9   5   1  10+  2   1   1  10+  6   1 
##  [25]  9   5   4   8   8  10+  6   6   3  10+  1  10+  4   2   2   1   6+  5+ 10+  4   9   9  10+  3 
##  [49]  1  10+  4  10  10+  9   6   6   2  10   4   7  10   2   1   1   7   1   2  10+  2   1  10+  1 
##  [73] 10+  4  10   2   5+ 10+  9   3   1   6   2  10+ 10+ 10+  7  10+  4  10+  3  10   5   3  10+  3 
##  [97] 10+  9   1+  1  10+  3   1  10+  1  10+  2   1   1+ 10+ 10+  1   2  10+ 10+ 10+  4  10  10+ 10+
## [121]  1   8   3  10   4   1  10+ 10+  4   7   1   1   7  10+  4   2  10+  5   3  10+  5   9  10  10+
## [145]  2   4   6+  5  10+ 10+ 10+  3   6   5  10+ 10+ 10+ 10+  9  10+ 10+  1+ 10+  6   2  10+  4  10+
## [169] 10+ 10+ 10+  7   7   7   9  10+  2   5  10+  4   1  10+  5  10+  2   2   8   6   1   9   6  10 
## [193] 10+  1+ 10   4   4  10+  7+ 10+</code></pre>
<p>and plot the estimated survival curve</p>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb300-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb300-1" tabindex="-1"></a>km_df1 <span class="ot">=</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> group, <span class="at">data=</span>surv_df1)</span>
<span id="cb300-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb300-2" tabindex="-1"></a><span class="fu">autoplot</span>(km_df1, <span class="at">conf.int =</span> F)</span></code></pre></div>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-199-1.png" width="672" /></p>
<p>In this sampling scheme it seems it’s common to get some very low values, which is probably quite unrealistic.</p>
<p>Some other assumptions / simplifications we’re making are:</p>
<ul>
<li>Censorings during the trial are completely at random (simulated via a Bernoulli distribution). In reality this is very unlikely; it’s far more likely that people become lost to follow-up for a reason, and that within the dataset the instances of this are not independent.</li>
<li>Censored data keep the same time as was generated by the exponential distribution. This will slightly skew our results.</li>
</ul>
</div>
</details>
<p>Having set up a function to simulate data for one trial, we can run it many times to estimate the power of this trial set up.
The extra pieces of information we need for this are:</p>
<ul>
<li>The significance level <span class="math inline">\(\alpha\)</span> - we will assume <span class="math inline">\(\alpha = 0.05\)</span></li>
<li>The test to be used - we will use the log rank test (as in Section <a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cp2logrank">D.2.2.2</a>).</li>
</ul>
<div class="exercise">
<p><span id="exr:unlabeled-div-126" class="exercise"><strong>Exercise D.13  </strong></span>Using the function you wrote in Exercise <a href="computer-practical-4---analysis-for-binary-and-survival-data.html#exr:survsim1">D.12</a> and the log-rank test, write a function to estimate the power of a trial set-up.</p>
<p>Assuming the same parameters as in Exercise <a href="computer-practical-4---analysis-for-binary-and-survival-data.html#exr:survsim1">D.12</a> and a significance level of <span class="math inline">\(\alpha=0.05\)</span>:</p>
<ul>
<li>Estimate the number of participants you need per trial group to achieve a power of 80%.</li>
<li>Suppose the clinicians decided to extend the trial so that <span class="math inline">\(t_{max}=20\)</span>. How many participants do you now need (approxiamtely) to achieve a power of 80%?</li>
</ul>
</div>
<details>
<summary>
Click for solution
</summary>
<div class="solution">
<p><span id="unlabeled-div-127" class="solution"><em>Solution</em>. </span></p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-1" tabindex="-1"></a>surv_sim <span class="ot">=</span> <span class="cf">function</span>(</span>
<span id="cb301-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-2" tabindex="-1"></a>    nsim,  <span class="co"># number of simulations to run</span></span>
<span id="cb301-3"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-3" tabindex="-1"></a>    alpha, <span class="co"># the significance level of the test</span></span>
<span id="cb301-4"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-4" tabindex="-1"></a>    npart, <span class="co"># number of participants per group (roughly)</span></span>
<span id="cb301-5"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-5" tabindex="-1"></a>    MC,    <span class="co"># median survival time - group C</span></span>
<span id="cb301-6"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-6" tabindex="-1"></a>    MT,    <span class="co"># median survival time.- group T</span></span>
<span id="cb301-7"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-7" tabindex="-1"></a>    p_cens, <span class="co"># probability of censoring for each observation</span></span>
<span id="cb301-8"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-8" tabindex="-1"></a>    t_max   <span class="co"># end point of trial</span></span>
<span id="cb301-9"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-9" tabindex="-1"></a>){</span>
<span id="cb301-10"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-10" tabindex="-1"></a>  H0_reject_vec <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NA</span>, nsim)</span>
<span id="cb301-11"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-11" tabindex="-1"></a>  </span>
<span id="cb301-12"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-12" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>nsim){</span>
<span id="cb301-13"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-13" tabindex="-1"></a>    df_i <span class="ot">=</span> <span class="fu">surv_data</span>(<span class="at">npart=</span>npart, <span class="at">MC=</span>MC, <span class="at">MT=</span>MT, <span class="at">p_cens=</span>p_cens, <span class="at">t_max=</span>t_max)</span>
<span id="cb301-14"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-14" tabindex="-1"></a>    log_rank_i <span class="ot">=</span> <span class="fu">survdiff</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> group, <span class="at">data=</span>df_i, <span class="at">rho=</span><span class="dv">0</span>)</span>
<span id="cb301-15"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-15" tabindex="-1"></a>    p_val <span class="ot">=</span> log_rank_i<span class="sc">$</span>pvalue</span>
<span id="cb301-16"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-16" tabindex="-1"></a>    H0_reject_vec[i]<span class="ot">=</span> <span class="fu">ifelse</span>(p_val <span class="sc">&lt;</span> alpha, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb301-17"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-17" tabindex="-1"></a>  }</span>
<span id="cb301-18"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-18" tabindex="-1"></a>  power.est <span class="ot">=</span> <span class="fu">mean</span>(H0_reject_vec)</span>
<span id="cb301-19"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-19" tabindex="-1"></a>  power.est</span>
<span id="cb301-20"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb301-20" tabindex="-1"></a>}</span></code></pre></div>
<p>We can now use this to find the sample size we need by experimenting with some values.</p>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb302-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb302-1" tabindex="-1"></a><span class="fu">surv_sim</span>(<span class="at">nsim=</span><span class="dv">100</span>, <span class="at">alpha=</span><span class="fl">0.05</span>, <span class="at">npart=</span><span class="dv">250</span>,<span class="at">MC=</span><span class="dv">5</span>, <span class="at">MT=</span><span class="dv">7</span>, <span class="at">p_cens=</span><span class="fl">0.1</span>, <span class="at">t_max=</span><span class="dv">10</span>)</span></code></pre></div>
<pre><code>## [1] 0.82</code></pre>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb304-1"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb304-1" tabindex="-1"></a>survsim_vec1 <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">20</span>)</span>
<span id="cb304-2"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb304-2" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>){</span>
<span id="cb304-3"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb304-3" tabindex="-1"></a>  survsim_vec1[i] <span class="ot">=</span> <span class="fu">surv_sim</span>(<span class="at">nsim=</span><span class="dv">100</span>, <span class="at">alpha=</span><span class="fl">0.05</span>, <span class="at">npart=</span><span class="dv">250</span>,<span class="at">MC=</span><span class="dv">5</span>, <span class="at">MT=</span><span class="dv">7</span>, <span class="at">p_cens=</span><span class="fl">0.1</span>, <span class="at">t_max=</span><span class="dv">10</span>)</span>
<span id="cb304-4"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb304-4" tabindex="-1"></a>}</span>
<span id="cb304-5"><a href="computer-practical-4---analysis-for-binary-and-survival-data.html#cb304-5" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(survsim_vec1)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>)</span></code></pre></div>
<p><img src="CT4H_notes_files/figure-html/unnamed-chunk-201-1.png" width="672" /></p>
<p>If we extend the trial duration to <span class="math inline">\(t_{max}=20\)</span>, the power given by a particular number of participants is now larger, because there are fewer censored observations and therefore more information. Some more experimentation with sample size would enable us to find a suitable number for this new scenario.</p>
</div>
</details>
<p>There are of course lots of ways we could refine and extend this, many of them similar to what we discussed in Section <a href="cp3sim.html#cp3sim">C</a>, for example:</p>
<ul>
<li>Running more simulations (100 is really not enough, but was chosen so that the file would compile - feel free to increase it)</li>
<li>Incorporating a better sampling scheme than SRS</li>
<li>Improving the drop-out / censoring modelling</li>
<li>Allowing the shape parameter to vary (though being careful of the implications on analysis)</li>
</ul>
<!-- ## Extension problem: Sample size by simulation (part II) {#cp2sim2} -->
<!-- If you have time, you could now combine the work we've done in this practical and the previous one to implement power simulation for a binary outcome trial. -->
<!-- If you've found the above fairly simple, this will be a good exercise to stretch your muscles. If not, then please still give it some thought, but feel free to look at the solution to see how the method applied to another approach. -->
<!-- Before starting, look back at Practical 3 and the steps to the simulation method and consider what you've to do to complete the exercise. -->
<!-- :::{.exercise} -->
<!-- Use simulation to find the appropriate size for a trial with a binary primary outcome variable. You can assume that the proportion of 'successes' in the control group is 0.65, and that the least clinically significant proportion we'd like to be able to detect is a treatment group proportion of 0.8. The trial should have a significance level of $\alpha=0.05$ and a power of $1-\beta = 0.8$. -->
<!-- ::: -->
<!-- <details> <summary> Click for solution </summary> -->
<!-- :::{.solution} -->
<!-- The steps within each simulation are: -->
<!--   - Simulate data using `rbinom` -->
<!--   - Run some analysis method on that simulated data -->
<!--   - Record whether $H_0$ was rejected -->
<!-- In the code below I've used the simplest type of analysis, a $t$-test on the absolute risk difference, but you could use any of the methods we've covered. -->
<!-- ```{r, echo=T} -->
<!-- binom_sim = function( -->
<!--   nsim,    # Number of simulations -->
<!--   N,       # Number of participants in each arm -->
<!--   piC,     # Assumed proportion in control group -->
<!--   piT      # minimum detectably different proportion in treatment group -->
<!-- ){ -->
<!--   H0_reject_vec = rep(NA, nsim) # to store 1 if H0 rejected, 0 if fail to reject H0 -->
<!--   for (i in 1:nsim){ -->
<!--     rC = rbinom(n=1, size=N, prob=piC) # generate numbers of successes -->
<!--     rT = rbinom(n=1, size=N, prob=piT) -->
<!--     pC = rC/N # Find estimates of proportions -->
<!--     pT = rT/N -->
<!--     p_pooled = (rC+rT)/(2*N) -->
<!--     z_stat = (pT - pC) / (sqrt(p_pooled*(1-p_pooled)*(1/N + 1/N))) -->
<!--     p_val = 2*(1-pnorm(z_stat, mean=0, sd=1)) -->
<!--     H0_reject_vec[i] = ifelse(p_val<0.05, 1, 0) -->
<!--   } -->
<!--   power.est = mean(H0_reject_vec) -->
<!--   power.est -->
<!-- } -->
<!-- ``` -->
<!-- Let's now try this for $N=100$, as a base point -->
<!-- ```{r, echo=T} -->
<!-- sim_vec7 = rep(NA, 100) -->
<!-- for (i in 1:100){ -->
<!--   sim_vec7[i] = binom_sim(nsim=100, N=100, piC=0.65, piT=0.8) -->
<!-- } -->
<!-- ggplot(mapping = aes(sim_vec7)) + geom_histogram(bins=10) -->
<!-- ``` -->
<!-- This is clearly too low so we can try a higher number - let's say $N=150$ -->
<!-- ```{r, echo=T} -->
<!-- sim_vec8 = rep(NA, 100) -->
<!-- for (i in 1:100){ -->
<!--   sim_vec8[i] = binom_sim(nsim=100, N=150, piC=0.65, piT=0.8) -->
<!-- } -->
<!-- ggplot(mapping = aes(sim_vec8)) + geom_histogram(bins=10) -->
<!-- ``` -->
<!-- This appears to be much closer - one could now finesse $N$ to fit some criteria on the proportion of simulations achieving the desired power. -->
<!-- ::: -->
<!-- </details> -->
<!-- There are of course lots of ways we could refine and extend this, many of them similar to what we discussed in Section \@ref(cp3sim), for example: -->
<!--   * Running more simulations (100 is really not enough, but was chosen so that the file would compile - feel free to increase it) -->
<!--   * Incorporating a better sampling scheme than SRS -->
<!--   * Improving the drop-out / censoring modelling -->
<!--   * Allowing the probability to vary in the data generation (this would be known as a *sensitivity analysis*). -->

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-jiang2012practical" class="csl-entry">
Jiang, Zhiwei, Ling Wang, Chanjuan Li, Jielai Xia, and Hongxia Jia. 2012. <span>“A Practical Simulation Method to Calculate Sample Size of Group Sequential Trials for Time-to-Event Data Under Exponential and Weibull Distribution.”</span>
</div>
<div id="ref-moertel1990levamisole" class="csl-entry">
Moertel, Charles G, Thomas R Fleming, John S Macdonald, Daniel G Haller, John A Laurie, Phyllis J Goodman, James S Ungerleider, et al. 1990. <span>“Levamisole and Fluorouracil for Adjuvant Therapy of Resected Colon Carcinoma.”</span> <em>New England Journal of Medicine</em> 322 (6): 352–58.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="cp3sim.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="cp-missing.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": true,
    "facebook": false,
    "twitter": false,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["CT4H_notes.pdf"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section"
  },
  "bookdown": null
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
